### ISSUE TITLE
Ability to depublish attachments

### ISSUE THREAD

**Issue by stefanw** [okfde/froide#108]
Make "Publish" and "Redact" further apart.

**Comment by jfilter** [comment]
IMO, very useful. It happens to be quite often that I accidentally upload incomplete/wrong documents. There are not visible but yet it still takes unnecessary space.

**Comment by arnese** [comment]
Solved!

**Comment by stefanw** [comment]
Depublication is not an option, but redaction is now also possible after publication.

**Comment by jfilter** [comment]
Why is depublication not an option? People make mistakes. I just received this feedback on Facebook (in German):

"Schön wäre dabei noch das hinzufügen von vorgefertigten PDF-Dateien. Des Weiteren wäre es toll, wenn man falsch hochgeladene Dokumente (bei Antworterhalt per Fax oder Brief) nachträglich löschen könnte. Ich habe beispielsweise eine zu große PDF (30MB) hochgeladen und würde diese gerne ersetzen."

**Comment by stefanw** [comment]
The idea is that FragDenStaat is a permanent record and archive. I could see allowing deletion up to some time after upload, but at some point it needs to be unremovable. We are still in the process of redesigning the whole file handling interface and we will incorporate people's mistakes.
