### ISSUE TITLE
Request status function should allow ofr multiple statuses to match real-world cases

### ISSUE THREAD

**Issue by marians** [okfde/froide#110]
The request status function requires me to set a distinct status for the entire request. In many cases, this is difficult for me for the following reasons:

My requests contained more than one question. The public body answered some of the questions without a fee, the remaining questions would have been answered against payment of a fee and some others wouldn't have been answered due to some reason like "personal data protection" or "information not available".

The option "Anfrage teilweise erfolgreich" (partly successfull) doesn't really fit perfectly in my eyes, since it gives no indication about the reasons why part of the request was unsuccessful.

My suggestion is to change the data model so that I can set more than one status if necessary.

![bildschirmfoto 2014-02-17 um 10 01 43](https://f.cloud.github.com/assets/273727/2183741/bb7425ee-97b2-11e3-9b5c-15483d3042f0.png)

**Comment by arnese** [comment]
I don't think this is useful anymore. Different status reports are also requested here: https://github.com/okfde/froide/issues/130
