### ISSUE TITLE
Filterfunktion für Liste gestellter Anfragen

### ISSUE THREAD

**Issue by ilf** [okfde/froide#133]
Unter https://fragdenstaat.de/account/ werden alle Anfragen des eignen Accounts tabellarisch gelistet, aber ohne Filterfunktion.
Wäre super, das nach "läuft noch" und "abgeschlossen", Datum und weiteren Kategorien filtern und sortieren zu können.

**Comment by ilf** [comment]
Ich habe diese Funktion gerade wieder gesucht. Diesmal würde ich gern meine eigenen Anfragen nach gestellter Behörde filtern. (Wollte auch die Suche dafür Zweckentfremden, aber die sucht nicht in Behördennamen). Dankeschön!

**Comment by arnese** [comment]
@stefanw just deployed this.
