### ISSUE TITLE
Creating new request through the API?

### ISSUE THREAD

**Issue by TomiToivio** [okfde/froide#136]
Currently it is not possible to create a new request through the API. Are you planning to implement this?

**Comment by TomiToivio** [comment]
Since we cannot use the API to make requests I just made an ad-hoc script that posts requests through the web interface. So it is essentially a spam bot for Froide. :)

**Comment by jaakkokorhonen** [comment]
Yeah we are now testing to ask at the begin of each month, last months' FOI requests from 12 ministries, just to publish what others have asked. This has already been rehearsed in http://tietopyynto.fi/r/141

The other case is to ask in a similar way, monthly the clear-cutting plans from the seven forestry centrals. This needs to be trained first by hand.

**Comment by jfilter** [comment]
@stefanw: Do you still plan to refactor the API to use Django REST framework? I would start working on the API myself. If you want to switch, I think now is a good time to do so. ;) 

(Check https://github.com/jfilter/frag-den-staat-app/issues/14)

**Comment by stefanw** [comment]
Yes, I'm in the middle of revamping the frontend and I'm considering to build it on Django REST Framework.

Or would you recommend going for a GraphQL API? It might facilitate certain actions (mutations) that are difficult to express in REST.

**Comment by jfilter** [comment]
OK, cool. ;) 

IMO, GraphQL is more future-proof and it would indeed simplify certain actions. For instance what fields to get when querying for FOI requests.

**Comment by akuckartz** [comment]
@jfilter GraphQL is more future-proof than what? And why?

**Comment by stefanw** [comment]
I replaced the API framework `tastypie` with `django-restframework` and also added OAuth application support. I did not version upgrade the URLs, but rather tried to keep the change backwards compatible in regards to URLs and return values. 

This allows third-party apps to ask users to login with their FdS-Account, see their requests and make requests on their behalf.

On FragDenStaat.de, the API/OAuth URLs are as follows:

OAuth-Application management: https://fragdenstaat.de/account/applications/
OAuth Authorize URL: https://fragdenstaat.de/account/authorize/
OAuth Token URL: https://fragdenstaat.de/account/token/

Available OAuth scopes: https://github.com/okfde/froide/blob/16b665f9575509bc183be171971883928411e4b8/froide/settings.py#L363-L371

Currently only Authorization Code and Implicit are supported for grant types.

Current user info (OAuth only):
https://fragdenstaat.de/api/v1/user/

The request endpoint accepts POST requests
https://fragdenstaat.de/api/v1/request/
according to the format of this serializer:
https://github.com/okfde/froide/blob/6faad313ad6e621547b975b661d7182d167125f3/froide/foirequest/api_views.py#L233-L248

More documentation is forthcoming.

**Comment by jfilter** [comment]
1. Currently, only HTTP and HTTPS are allowed for the scheme of the redirect URIs. To use it in the app, we have to allow custom schemes. As far as I can see, you could only do it by adding schemes to the setting `allowed_redirect_uri_schemes`. <https://github.com/evonove/django-oauth-toolkit/blob/master/docs/settings.rst#allowed_redirect_uri_schemes> I chose `fragdenstaat` as a scheme for now.

2. For the implicit mode, there is no refreshing of the auth token. So the default expiration time of 60 minutes is quite limiting. I think we should increase it to something like 6 months.

**Comment by stefanw** [comment]
Added in okfde/fragdenstaat_de@143014172be14aa01e11409ccbe551b14fa34943

**Comment by jfilter** [comment]
I am a little bit lost. There seems to be no clear answer what grant to use. Also, there is no way to store secrets in the source code of a mobile app. That's why the implicit flow on mobile apps seems so popular. But it wasn't built for that use case, and it's not as secure as the other grants.

https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2#grant-type-implicit
https://stackoverflow.com/questions/17427707/whats-the-right-oauth-2-0-flow-for-a-mobile-app
https://medium.com/@justinsecurity/mobile-apps-and-oauths-implicit-flow-68e72c6515a1

To do it properly, I had to run a server as a middleman as Facebook writes:

> We recommend that App Access Tokens should only be used directly from your app's servers in order to provide the best security. For native apps, we suggest that the app communicates with your own server and the server then makes the API requests to Facebook using the App Access Token. 

https://developers.facebook.com/docs/facebook-login/security#appsecret

**Comment by jfilter** [comment]
I talked with Stefan in brief and to sum it up, we need [PKCE](https://oauth.net/2/pkce/) but it's not implemented in the lib Froide uses to handle oauth: https://github.com/evonove/django-oauth-toolkit/issues/566

**Comment by jfilter** [comment]
The reference has to to be in the following format: 'string:string'. [Source](https://github.com/okfde/froide/blob/6faad313ad6e621547b975b661d7182d167125f3/froide/foirequest/validators.py#L34)

**Comment by stefanw** [comment]
Reference should be optional (used for campaign tracking), if it's not, it's a bug.
