### ISSUE TITLE
OperationalError no such table: auth_user

### ISSUE THREAD

**Issue by gabelula** [okfde/froide#139]
I'm getting an error when trying to add a user through the django admin (http://127.0.0.1:8000/admin/account/user/add/).  It says "OperationalError no such table: auth_user". It is trying to access that table but we don't have it, the same when trying to change information about the superuser via the admin.

**Comment by alxwang2020** [comment]
still can not figer out after installed sqlite

>

**Comment by sjzombie** [comment]
having similar error , still unable to understand how to fix it

**Comment by itxDeeni** [comment]
Have you found the solution to this error?
