### ISSUE TITLE
 irregeleitete Antworten an abgeschlossene Anfragen werden nicht abgewiesen

### ISSUE THREAD

**Issue by HappyPony** [okfde/froide#144]
Ich rege an, dass irregeleitete Antworten an abgeschlossene Anfragen abgewiesen werden.

Begründung:
die Behörde hat die Antworten, die zu den Anfragen https://fragdenstaat.de/a/8759 und https://fragdenstaat.de/a/8710 gehören, fälschlicherweise an diese bereits früher geschlossene Anfrage https://fragdenstaat.de/a/8528 [1] gesendet und das FDS-System hat fälschlicherweise die Antwort an [1] angehängt.

Kann der FDS-Admin die irregeleitete Antworten an richtige Anfragen umhängen?

 Ich rege an, dass irregeleitete Antworten an abgeschlossene Anfragen vom FDS-System abgewiesen werden.

**Comment by arnese** [comment]
not useful at this moment.
