### ISSUE TITLE
nice-to-have: Nummern von Anfragen im Profil einblenden

### ISSUE THREAD

**Issue by HappyPony** [okfde/froide#168]
ich rege an, Nummern von Anfragen im Benutzer-Profil in der Überschrift einzublenden. Ich habe über 100 Anfragen auf meiner fragdenstaat.de-Profilseite und mit so einer Nummer - wie in den Betreffzeilen der EMails - könnte ich ungemein viel Zeit bei der Suche nach einer bestimmten Anfrage sparen.

Danke für fragdenstaat.de!

**Comment by arnese** [comment]
Durch die Suche in den eigenen Anfragen ist dies jetzt möglich.
