### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by catcosmo** [okfde/froide#171]
- [x] Include terms in paranthesis in search. (So far, search term "Landtag Niedersachsen" does not return public body "Niedersächsischer Landtag (Niedersachsen)")
- [ ] Add possibility to filter results (e.g. by status, federal state, category, costs, escalation)
- [ ] Add sorting (e.g. by date, alphabet, status)
- [ ] Add listing results by numbers (e.g. 10, 20, 50, all; per page)
- [x] Add number of results
- [x] Harmonize both types of searches

**Comment by arnese** [comment]
Search term "Sonderberich" should also give results with "Sonderbericht"

**Comment by arnese** [comment]
transferred to https://github.com/okfde/froide/issues/255
