### ISSUE TITLE
503 on large API requests

### ISSUE THREAD

**Issue by ffalt** [okfde/froide#177]
seems like I'm able to kill the API with a large "limit"-parameter.

request: /api/v1/request/?limit=1000
wait: about 30 seconds
answer: 503 Service Unavailable

**Comment by stefanw** [comment]
We should set [max_limit](https://django-tastypie.readthedocs.org/en/latest/resources.html#max-limit) on resources. For the `request` resource no limit is especially bad because it also gives you all messages and all attachments of all messages for a request.

**Comment by jfilter** [comment]
@arnese: Stefan fixed it some time ago (and also changed the whole API library). This can be closed.

**Comment by arnese** [comment]
fixed by @stefanw
