### ISSUE TITLE
black out of specific document is buggy

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/froide#206]
I receive a http-500 error when I press save button after blacking out a specific document. Like @arnese suggested I've created this issue. I can black out other documents and I tried Firefox 49 and Edge but no success. It must be server sided. I talk about this document: https://fragdenstaat.de/anfrage/fakultatsratsprotokolle-der-fakultat-4/#nachricht-54119

**Comment by arnese** [comment]
Moved to https://github.com/stefanw/froide-redact/issues/9
