### ISSUE TITLE
Redaction issue in email text

### ISSUE THREAD

**Issue by arnese** [okfde/froide#212]
When names and text elements are deleted from "Redacted text" area, this blackens the area, but still makes it possible to copy the text from area. Only when text is replaced by other text this doesn't happen.

**Comment by fin** [comment]
huh, 2 years ago (the version we're running on .at *cough*), redaction was implemented by creating an image pdf. has this changed?

**Comment by arnese** [comment]
Nope. Should have specified: This is about redaction in text of emails, not in attachments.

**Comment by GiantCrocodile** [comment]
I expected this but I don't feel like this should be changed. I dislike how hard it is to read redacted text sometimes but changing the copy feature - well please not. I love to copy data which is redacted because I need it for e-mails or forwarding or internal resources so I would have to copy the text by hand.

**Comment by fin** [comment]
this only happens when you're logged in (on your own requests), or when you're logged in as admin (maybe?).

try this in an incognito window:
https://fragdenstaat.de/anfrage/weisungen-des-jobcenters-jobcenter-landkreis-amberg-sulzbach-und-die-stadt-amberg/

**Comment by arnese** [comment]
Hm, not really. Happens when I manually delete text so it becomes redacted, not with the automatic redactions. But it's all a bit unclear, because I cannot always reproduce it either. 

https://fragdenstaat.de/anfrage/weisungen-des-jobcenters-jobcenter-landkreis-amberg-sulzbach-und-die-stadt-amberg/#nachricht-65210
In your request, for example I manually deleted the word "Paris" from the line "Die Adresse in Paris ist die aktuell gültige". Now more is redacted, while the text behind it can still be copied (but not "Paris", actually)

**Comment by fin** [comment]
oh right, mea culpa. (better restore that word though, not my request ;) )

**Comment by stefanw** [comment]
The 'algorithm' behind the redaction effect [is a monster based on Python's SequenceMatcher]((https://github.com/okfde/froide/blob/master/froide/foirequest/templatetags/foirequest_tags.py#L42-L115). Probably needs a more human text (not code) centric diffing library (not 100% that is the problem though).

**Comment by arnese** [comment]
This particular case is solved by now.
