### ISSUE TITLE
Add references header to outgoing emails 

### ISSUE THREAD

**Issue by corny** [okfde/froide#214]
Please add email headers to enable grouping of emails related to the same freedom of information request. Github adds headers like these:

```
In-Reply-To: <okfde/froide/pull/93@github.com>
References: <okfde/froide/pull/93@github.com>
```

Froide should add something similar.

**Comment by stefanw** [comment]
GitHub mirrors Issue/PR discussions via email so you never reply to the email, you reply to the virtual thread.

Froide should behave more like an email client. The headers are supposed to reference messages from before to allow threaded display. I don't know if we should add a `References` header when there's no message referenced (e.g. first message in a request). Looking into it some more.
