### ISSUE TITLE
Missing File Type/File Size for some PDFs

### ISSUE THREAD

**Issue by jfilter** [okfde/froide#216]
Check: https://fragdenstaat.de/anfrage/ifg-antrag-weisungen-und-zielvereinbarungen-3/

You can see here, that the size and the `filetype` for the attachment does not get set:

https://fragdenstaat.de/api/v1/request/?slug=ifg-antrag-weisungen-und-zielvereinbarungen-3

It only occurs on a hand full of requests: https://www.google.de/?gfe_rd=cr&ei=zT9zWcfKGIPZ8AfU0pPYDA#q=site:fragdenstaat.de+%22(0+Bytes)%22

**Comment by arnese** [comment]
That's actually not a bug, but pure laziness from my side. I uploaded those attachments manually because I got them from another source. Will add the filetypes later.
