### ISSUE TITLE
Asking for mediation: problem with too big attachments

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/froide#217]
If you ask for mediation and your request includes big attachments, it will fail because the e-mail max size is reached. At least this is what I would expect. My request had 100 mb when I downloaded the zip.

**Comment by stefanw** [comment]
Good point. A check for size should be made before including the attachments. Or making the files downloadable with a link instead of including as attachments.

**Comment by GiantCrocodile** [comment]
Maybe this is why I get an 404 http error from Nginx when I try to use this function with one of my requests ... although I'm not sure this is related.

**Comment by GiantCrocodile** [comment]
`Good point. A check for size should be made before including the attachments. Or making the files downloadable with a link instead of including as attachments.`

I think it should do a file size check and if it fails, then it should do a downloadable link.

**Comment by arnese** [comment]
Fixed. Now attaching list of documents - if too big, only as a reference with link.
