### ISSUE TITLE
professional regulatory complaints (Fachaufsichtsbeschwerde) feature

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/froide#218]
Maybe we should add an option to send a generated professional regulatory complaints (Fachaufsichtsbeschwerde) because it feels like a lot of FOIA requests are handled wrong and this would increase complaints number in gov statistics and maybe changes internal behaviour/structure of gov agencies. Furthermore it could be a cheap alternative to last option before suing and filing legal caveat.

**Comment by arnese** [comment]
Where's the additional value of this when we already have complaints to IFG commissioners?

**Comment by GiantCrocodile** [comment]
These are two different kinds of complaints and it may make sense to ask for a gov agency internal review. The gov agency could notice themself that the decision of the person who worked on your case is wrong. It may be faster or better to have two complains open: one at IFG commissioners, one at the gov agency themself. This could result in faster and better review results. If the internal review sucks, you still have the IFG commissioner to take care of it.

**Comment by arnese** [comment]
Hm. Do you have some experience to show how this works and how effective it is?

**Comment by GiantCrocodile** [comment]
That's the main problem here. I don't know how effective it is nor how a good complaint looks like. I would have expected this feature to proof it. I can try to get some experience with it by hand and report my experience afterwards.

**Comment by arnese** [comment]
Any experience so far?
