### ISSUE TITLE
Move history of request back to top

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/froide#220]
In the mobile version of FROIDE the history of a request is at the bottom of the page. This is bad usability because it forces the user to scroll a lot to get to where he wants to be. It should be back at top of the page again.

**Comment by arnese** [comment]
Please move this to the app: https://github.com/jfilter/frag-den-staat-app/issues

**Comment by GiantCrocodile** [comment]
Hello @arnese. I didn't use the app but visited the website in my mobile browser. So are you sure I should create the issue there?
