### ISSUE TITLE
Untätigkeitsklage generieren

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/froide#221]
Wenn Anfrage in 3 Monaten nicht bearbeitet und eine Empfangsbestätigung vorliegt, dann generiere Untätigkeitsklage gegen Behörde als ODT und PDF.

**Comment by arnese** [comment]
Das geht so einfach nicht, weil mit der Generierung von Klagevorlagen auch Haftungsfragen aufkommen. Mehr Hilfe bei Untätigkeitsklagen ist aber gewünscht. Weitere hier: https://github.com/okfde/fragdenstaat_de/issues/79

**Comment by GiantCrocodile** [comment]
Oder man hinterlegt irgendwo ein Template für eine Untätigkeitsklage und erklärt, dass die ggf. fehlerhaft ist und nur auf eigene Gefahr hin verwendet werden kann. Aber selbst beim Missachten vom/bei Unwissenheit übers Rechtsträgerprinzip dürfte eine Untätigkeitsklage doch in der Regel nicht baden gehen. Ansonsten wüsste nicht, was man falsch machen sollte.

**Comment by rugk** [comment]
done: https://fragdenstaat.de/blog/2022/04/20/der-fragdenstaat-klageautomat-ist-da/
