### ISSUE TITLE
Uploaded Postal Response as JPG -> Unable to Redact PDF

### ISSUE THREAD

**Issue by jfilter** [okfde/froide#222]
See here <https://fragdenstaat.de/anfrage/brandverhutungsschauen-an-schulen/redact/31548/>

**Comment by arnese** [comment]
Please see #181 for more. We should either make redaction of non-pdfs possible or disable redaction for non-pdfs

**Comment by jfilter** [comment]
I vote for only allowing PDF uploads.

**Comment by stefanw** [comment]
I think the right flow would be to handle documents and redaction on documents in PDF. Upload of one or more images should lead to the creation of a PDF document.
