### ISSUE TITLE
Doppelte Vorlage bei Änderung

### ISSUE THREAD

**Issue by astoorangi** [okfde/froide#226]
Wenn beim Stellen einer Anfrage die Vorlage angepasst wird, wird die "normale" Vorlage erneut um die geänderte Vorlage gepackt, sodass alle Standarttexte doppelt verschickt werden.
Beispiele:
https://fragdenstaat.de/anfrage/rede-der-gleichstellungsbeauftragten-des-bamf-auf-personalversammlung/
https://fragdenstaat.de/anfrage/aktenplane-des-rbks/

**Comment by stefanw** [comment]
Fixed in 7495d5f1185fcc2bbbbf6759c15b22616f700905
