### ISSUE TITLE
Wrong link in the Finnish version

### ISSUE THREAD

**Issue by emilfihlman** [okfde/froide#229]
"Napsauta tästä mennäksesi sivulle tietopyynto.fi" links to http://www.abgeordnetenwatch.de/ instead of tietopyynto.fi

![image](https://user-images.githubusercontent.com/9070088/35521187-cc6c0c28-0521-11e8-8032-aeec3f035d74.png)

**Comment by stefanw** [comment]
This is likely a translation issue, please contact the provider of that service directly. The current version of Froide does not have the mentioned feature anymore.
