### ISSUE TITLE
Encrypt non-public documents

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/froide#231]
It would be nice to be able to encrypt your non-public files. The private key should be never stored on Froide and the redacted file for public shouldn't be encrypted. This protects users from a froide platform being hacked, gov regulations and some shady admins: You don't have to trust anyone for your non-redacted files.

**Comment by jfilter** [comment]
This would add a lot of complexity to the mix. I think it would be better to not store the non-redacted files at all (or only for a limited amount of time e.g. one month). #datensparsamkeit

**Comment by GiantCrocodile** [comment]
I don't think so @jfilter. Right now I use the original files on Froide as a backup and to write statements, etc. about my cases. For example I often redact stuff for public which I would need if I wanna write a legal caveat. Also you can't ask the gov agencies which monitor FOiA requests and support you without the original documents. This would make mediation harder.

**Comment by arnese** [comment]
I don't see any of this happening. Sensitive documents are not processed by FragDenStaat anyways because they wouldn't be given out by authorities. Keeping files non-public is enough and we should invest in not being hacked and not having shady admins. More sensitive files should be kept encrypted elsewhere.

**Comment by jfilter** [comment]
Okay, Clemens I get your points and with sufficient funding it would have been a feature to discuss. I disagree with Arne and see in fact the danger of shady admins. (Power always corrupts). However, with the little money FdS currently has, it should focus on the core features and outsource the rest. (IMO the newsletter shouldn’t be done in froide e.g.)
