### ISSUE TITLE
Annotation of documents

### ISSUE THREAD

**Issue by arnese** [okfde/froide#233]
I wonder if we should make annotations possible and - if yes - which tool to use. Something like this might be interesting: https://www.patentoppositions.org/en/drugs/4f1081fb04a7f937af000016/patent_oppositions/4fb3beca04a7f95c9f000011

**Comment by jfilter** [comment]
Maybe we start off by integrating an existing solution: https://web.hypothes.is. They allow to annotate web sites and PDFs.

**Comment by stefanw** [comment]
I get the idea that froide should focus on core features and outsource the rest. However, as the main project using froide needs to be really privacy friendly (due to the environment in which it operates), outsourcing to third-party services is a non-starter. I'd rather reuse code or redeploy services.

The example that @arnese mentioned should be feasible to reuse.

**Comment by jfilter** [comment]
Okay, I agree. Maybe we can *literally* outsource it by delegating this task to somebody else. There seem to be some existing solutions but maybe we have to adapt it to our needs. 

https://github.com/instructure/pdf-annotate.js which is based on https://github.com/mozilla/pdf.js/

Let's tag issues as `help wanted` and if we have enough (let's say 5), we call on Twitter for help. I'm pretty sure that there are people out there who want to help. But right now, it's not so easy to get started.

**Comment by akuckartz** [comment]
+1 to using hypothes.is (either software or service)

**Comment by GiantCrocodile** [comment]
Whatever we do, I explicitly vote for a self-hosted solution so no third party service is used or involved with our documents.

**Comment by jfilter** [comment]
At the prototype fund demo day, [Andreas Pittrich](https://github.com/rhotep) suggested taking a look at https://github.com/paperhive by [André Gaul](https://github.com/andrenarchy).

**Comment by jfilter** [comment]
I stumbled upon http://neonion.org/, a self-hosted text-annotation tool developed by the FU Berlin. (Java though)
