### ISSUE TITLE
Redaction is completely unreliable in FireFox

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/froide#237]
It is impossible to select the things you wanna redact correctly and even then, it just redacts more or less than you did select.

**Comment by stefanw** [comment]
I know it's not perfect. PDF rendering is not an easy problem and we are relying on [PDF.js](https://github.com/mozilla/pdf.js/) to make it happen. I'm sure we can improve on some usability aspects, but there's not much we can do about the PDF rendering/text matching itself. I just upgraded to latest version of PDF.js, maybe it's a bit better now.
