### ISSUE TITLE
Redaction creates black page

### ISSUE THREAD

**Issue by mschwarzer** [okfde/froide#238]
The result of the reaction of an PDF has a full black page instead of only the selected lines. I'd like redo the redaction by myself but there is no way in undoing the first redaction.

See PDF from: https://fragdenstaat.de/anfrage/liste-aller-2017-erteilten-urteile-des-schleswig-holsteinischen-oberlandesgericht/

**Comment by stefanw** [comment]
There is a way: click "Redact" next to the original PDF which should still be listed.

There's also a (bit of a clunky) undo in the PDF redaction tool: the circly arrows on the left are undo and redo.

But yes: the text selection is not very nice and sometimes does a rectangle selection instead. Will look into it.

**Comment by mschwarzer** [comment]
I already tried to react the original PDF but I don't have the permissions to do so (403 - Verboten). The undo button in the reaction tool doesn't work as well.

Can you give me the permission to fix this? For now this should be enough as long as nobody else is having the same problem.

**Comment by stefanw** [comment]
I changed permissions, it should be possible now. I also applied some fixed to undo and added a new "image-only" button so that text selection doesn't interfere with drawing a rectangle. Please try it!
