### ISSUE TITLE
Feature: Anfrage zurückziehen

### ISSUE THREAD

**Issue by ilf** [okfde/froide#24]
Es gibt Fälle, in denen man eine Anfrage zurückziehen will. Das ist bisher nicht möglich.

**Comment by akuckartz** [comment]
:+1: Ich habe dieses Feature bereits bei einer eigenen Anfrage vor ein paar Monaten vermisst und dabei Zeit für die Suche danach aufgewendet. Fälschlicherweise wird bei der Anfrage deshalb bis jetzt  der Wecker angezeigt, obwohl der Behörde kein Vorwurf verzögerter Bearbeitung zu machen ist.

**Comment by arnese** [comment]
Das ist inzwischen möglich. Statusänderung und dann gibt es einen Prompt, zusätzlich eine Nachricht zu schreiben.
