### ISSUE TITLE
Allow users to suggest new public bodies

### ISSUE THREAD

**Issue by AleksiKnuutila** [okfde/froide#240]
Maintaining an exhaustive list of public bodies is hard, so it would be helpful for users to be able to directly add public bodies. I believe this functionality existed in a previous Froide versions, but the current version appears to suggest emailing the admins with additions. Am I right to think this is not possible with Froide - and if not, could I suggest it as an added feature?

**Comment by jfilter** [comment]
It does not solve your problem directly but there is an admin role to solely manage public bodies. So if you find somebody who is eager to help out, they can do the changes directly.

**Comment by jaakkokorhonen** [comment]
We don't have capacity to maintain a list manually. There are more organizations under publicity law than what we have FOI requests per year in Finland.

**Comment by jfilter** [comment]
I think nobody objects this feature. Feel free to send a pull request.

**Comment by stefanw** [comment]
We had this feature directly in the request process (e.g. making a request and proposing a new authority). The list of fields for authorities has grown a bit, but I agree that an easy proposal process needs to exist.
@jaakkokorhonen just to inform our decision making process further: would you be able / need to confirm the proposed authorities or should they immediately become active?

**Comment by AleksiKnuutila** [comment]
I think we would be able to confirm the authorities. In my view, the earlier user journey, where users can add a public body and write the message, but the message wouldn't be sent before the authority is confirmed, worked quite well.

**Comment by stefanw** [comment]
@AleksiKnuutila Good to know. What kind of information would you say is required at a minimum in order to create a public body?

**Comment by arnese** [comment]
Moved this to https://github.com/okfde/froide/issues/254
