### ISSUE TITLE
Creating a region in the admin does not work

### ISSUE THREAD

**Issue by rixx** [okfde/froide#242]
To create a Jurisdiction (as per the development guide) I need a georegion. To create a region, I need to use the fancy input to add a geometry (which does not work for me, but maybe I just can't use the input method correctly), *and* provide the "part of" field for **that** geo region. Which I can't because there is no geo region there already.

(The ForeignKey ``part_of`` of ``GeoRegion`` is set to ``null=True``, but also needs a ``blank=True`` to signal the Django admin that leaving this field empty is alright. The same goes for the ``region`` field of ``Jurisdiction``)

**Comment by stefanw** [comment]
I made `region` optional on `Jurisdiction` and `part_of` optional on `GeoRegion`. The missing  `blank=True` was just an oversight.

Please note that froide is supposed to be used as a set of apps in a Django project that runs it. The main user of froide is [fragdenstaat_de](https://github.com/okfde/fragdenstaat_de). There you can find [a management command to populate the GeoRegions](https://github.com/okfde/fragdenstaat_de/blob/master/fragdenstaat_de/theme/management/commands/load_georegion.py).

The development guide is sadly not up-to-date, but I guess you already noticed. Thanks for the improvements!
