### ISSUE TITLE
Import of all cities and towns in the state of Brandenburg

### ISSUE THREAD

**Issue by clusti** [okfde/froide#250]
The administrations of the cities and communities in the state of Brandenburg are unfortunately missing. 
Fortunately, the veterinary offices are available. There are 417 cities and towns in Brandenburg. 

A CSV File is available under: 
https://service.brandenburg.de/lis/list.php?page=kommunen_p

**Comment by stefanw** [comment]
Please open FdS specific issues here:
https://github.com/okfde/fragdenstaat_de

Landkreise, kreisfreie Städte, Ämter, amtsfreie Gemeinden und Städte were imported, the other dataset is missing email and other contact info.
