### ISSUE TITLE
Additional determination of status of FOI requests

### ISSUE THREAD

**Issue by clusti** [okfde/froide#252]
It might be useful, also because of a statistical evaluation, if the following statuses are still included for FOI requests

* In opposition proceedings "Im Widerspruchsverfahren"
* In process / examination by the Federal Commissioner for Data Protection and Freedom of Information "In Bearbeitung/Prüfung durch die Bundesbeauftragte für Datenschutz und Informationsfreiheit"
* In the lawsuit "Im Rechtsstreit"

In this case, it could be useful if the corresponding status can also be easily visualized in the query, for example, at the edge. By appropriate boxes. It should be recognizable whether, for example, after a notice of objection, the request was successfully answered or only after involvement of the Federal Commissioner for data protection and freedom of information.

It could also be added here whether the Commissioner for Data Protection and Freedom of Information has made a positive or negative statement here.

**Comment by arnese** [comment]
Thank you. We already have some issues for status. Have a look at https://github.com/okfde/froide/issues/135
