### ISSUE TITLE
Proposal to better handle non-FOI requests - Additional filter to detect non-FOI requests

### ISSUE THREAD

**Issue by clusti** [okfde/froide#253]
Again and again there are non-FOI requests in the system. For example, the demand for bank details, pension cards, changes to bank details, request for forms.

For this purpose, one could establish a simple filter that explicitly explores for certain words the user points out that it is not about personal information or personal concerns. Especially through a pop-up and even clearer font. Alternatively, it would also be a way to unlock those requests only by a moderator.

Examples of some keywords would be:

Bank details
Pension id card
Pension calculation
Change form
SEPA Direct Debit
Submission form
Request form

**Comment by stefanw** [comment]
It's true that FdS is not the right platform for these requests, but some of the requests are actually answered with the right information (so it is helpful to people). I would like to find a way to not just reject these requests but channel them to a solution (likely outside of FdS).

**Comment by alehaa** [comment]
Every few days I see requests where someone includes his private identification number and name for communications with the german "Beitragsservice". I think it's fine to give the users a platform for easy communication with authorities, but in some cases people might not understand that this request is actually public. I miss some kind of "report" button, so other users can protect them from leaking sensitive information.

**Comment by arnese** [comment]
I hope that with the new feature of reporting these requests this won't be a big problem anymore.

**Comment by alehaa** [comment]
@arnese I discovered the feature today and think this will satisfy the needs of this issue. Thanks for releasing the feature.

**Comment by arnese** [comment]
It seems this is no longer a (very big) issue.
