### ISSUE TITLE
Can't sent message "Sie müssen eine Begründung angeben."

### ISSUE THREAD

**Issue by jfilter** [okfde/froide#256]
https://fragdenstaat.de/anfrage/kommunikation-mit-christoph-groner-cg-gruppe/send/message/#write-message

Every time I click 'send message' I get the error response:

"Sie müssen eine Begründung angeben."

![screen shot 2018-07-24 at 22 57 08](https://user-images.githubusercontent.com/3450307/43165801-1d829138-8f95-11e8-9960-a1fa06a4aaa3.png)

**Comment by arnese** [comment]
Huh. That's actually an error you get when you want to send a message to the FOI commissioner without adding a reason. Seems to be mixed up.

**Comment by stefanw** [comment]
It's also correct for send message if there's no overdue state and you have not changed the message. The overdue message is ready to be sent as is though.
