### ISSUE TITLE
Schwärzungen in Texten editieren

### ISSUE THREAD

**Issue by markuspoerschke** [okfde/froide#260]
Wenn eine Antwort als E-Mail erfolgt, sind ggf. weitere Schwärtzungen notwendig oder zu viel Text wurde geschwärtzt.

**Beispiel 1: nicht ausreichende Schwärzung**
Die Datenschutzbeauftragte wendet sich an die Behörde und schreibt den Mitarbeiter dort mit seinem Namen an. Da das "Sehr geehrte(r) Herr/Frau" erst weiter unten erscheint, wird es nicht geschwärzt. Eine Schwärzung erfolgt hier über den Button "Problem?" und muss dann von einem Admin manuell erfolgen.

**Beispiel 2: Antwort in weitergeleiteter E-Mail geschwärzt**
Befindet sich die Antwort (z. B. eine Stellungnahme einer Stadt gegenüber der Datenschutzbeauftragten) in einer weitergeleiteten E-Mail, so ist der Text oft unter der Signatur zu finden. Dadurch wird die Antwort geschwärzt. Hier sollte es möglich sein, die schwärzung im Text wieder zurückzunehmen.

**Comment by k4l0ph41n** [comment]
**Beispiel 3: nicht ausreichende Schwärzung**
Wird der Empfängername falsch geschrieben "Sehr geehrter Herr Mülller", wird der Name nicht geschwärzt.

[Siehe hier](https://fragdenstaat.de/anfrage/open-source-anwendungen-und-betriebssysteme-30/#nachricht-377128)

**Comment by stefanw** [comment]
> Wird der Empfängername falsch geschrieben "Sehr geehrter Herr Mülller", wird der Name nicht geschwärzt.

Nein, hier wurde eine Anrede verwendet "Bester Herr X", die nicht gerade Standard ist und die wir nicht erkannt haben.

Was wir verhindern wollen, dass Nutzer E-Mails von anderen direkt bearbeiten können. Es braucht also ein Schwärzungs-Interface für Text selbst, was eine etwas kniffligere UI-Aufgabe ist.

Ideen werden gerne entgegen genommen.

**Comment by rugk** [comment]
Einfach nur ein Interface, wo man Text markieren kann, der dann schwarze Balken bekommt?
Also kein Texteingabefeld, sondern nur eins wo man Text markiert?

Gesendet werden dann die Zeichenpositionen, und der Server "schwärzt" eben diese Zeichen? (so ähnlich funktioniert doch auch das PDF-Textschwärzungstool, also das, wo es sum Text geht.)

**Comment by stefanw** [comment]
Klingt schon richtig, aber man soll ja auch entschwärzen können. Das Tools selbst ist eben nicht ganz trivial.

**Comment by arnese** [comment]
Das ist inzwischen möglich.
