### ISSUE TITLE
Getting started documentation outdated

### ISSUE THREAD

**Issue by sliminas** [okfde/froide#261]
I just managed to setup the django app locally on my machine and noticed that the content of the documentation at https://froide.readthedocs.io/en/latest/gettingstarted/ doesn't match the content of 
https://github.com/okfde/froide/blob/master/docs/gettingstarted.rst . 

Is this intentionally?

Especially the part with the geospatial db backend would have saved me quite some time if I would have seen it already on readthedocs as well.

**Comment by stefanw** [comment]
The documentation build on readthedocs was broken. Latest docs are now building again. Sorry for that.
