### ISSUE TITLE
Do not send users passwords via mail

### ISSUE THREAD

**Issue by rugk** [okfde/froide#263]
When registering, you get a mail with a password in the mail.
That is a really old and insecure practice, e.g. because mail is generally not really secure. ALso, you don't want users finding their password in their inbox.

So best practice is:
* Send only a verification link and let the user set the password on the site that appears.
* Or let the user set the password before.

**Comment by stefanw** [comment]
I can see the point. The verification link does (usually) prompt a password change (not for our current campaign though!). My thinking is that your account depends on the security of your email account (as you may reset the password from there). But: Having the password in your inbox means that someone inside your email account has access to your account without resetting the password. This is obviously bad.

I don't want to do the first option and I'm looking into the second option. I don't quite know how though. I want to mark the user verified when they click they link, but what happens if they don't enter a password, but switch to a different page?

**Comment by rugk** [comment]
> I don't want to do the first option and I'm looking into the second option.

Your command afterwards implies the opossite, but in any case, the 1 is a common way choosen by many websites. Just try it...

> I want to mark the user verified when they click they link, but what happens if they don't enter a password, but switch to a different page?

Require password on next login?

**Comment by GiantCrocodile** [comment]
Set the account verified when a password has been set - not when a link has been clicked. Keep the link active for a week or until a password has been set.

**Comment by stefanw** [comment]
@GiantCrocodile I don't think that's a good user friendly option. Giving a password should not be an immediate requirement in order to make a request. This will just encourage people to make up bad passwords on the spot. I prefer setting a password in your own time and logging in through one-time-use links via email in the mean time.

**Comment by rugk** [comment]
> Giving a password should not be an immediate requirement in order to make a request.

You've already filled in the request before, so you are already "hooked". In order to finish that request, you just need to set a password then.
That is a well-known and -understood pattern as many websites use it, so users won't complain about that. Also, as I said you are "hooked", so you know you have to do this before the process is finished. In such a state the user is unlikely to cancel.
If users are supposed to set the password "later" "in tehir own time", this will never happen. You know, procrastination and so on.

As such, IMHO this would be the best solution.
You could maybe still send the request filled out before when the link is clicked, but still require to set a password for any further usage of this account. If the user declines, and tries to login later, maybe you then just need to resent the confirmation mail until the finally click taht link _and_ set a password.

**Comment by jfilter** [comment]
Don‘t require a password to login. If you don’t set a password, you can always login via a _magic link_ (also called _passwordless_).

**Comment by rugk** [comment]
@jfilter I do personally consider this an antipattern (_passwordless_) that gets familar nowadays. It's insecure and so I consider it worse than the current login method. But as long as it is optional (i.e. you still can set a password), it's okay to use.
I still would not recommend it.

**Comment by jfilter** [comment]
Thanks for sharing your opinion. Can you support your claims with some examples or references?

Currently, there are no requirements when setting the password such as a minimum length or “don’t choose an obvious password”. This is very bad.

**Comment by stefanw** [comment]
@rugk Can you point us to something to support the *passwordless* is insecure claim? I would think it moves security to your email account which a user might protect better (and likely has more security resources) than some random website.

I think I can get away with setting no password on validating email addresses and offering users to set a password in various places. Password validation is a good point, [Django supports it](https://docs.djangoproject.com/en/2.1/topics/auth/passwords/#module-django.contrib.auth.password_validation), we should enable it.

**Comment by GiantCrocodile** [comment]
I didn't realize that setting a password or having none at all is the discussions topic. For me it sounds like we will have a password to set but it may be problematic in cases where the user cancels the password setting process.

If we discuss either password or a magic link: I disagree about a magic link. Froide or FragDenStaat isn't something special or some high risk level application and thus I don't see any reason why a regular user should care about this site much more than any other site. Keep in mind: This is in point of view of an ordinary user, not from technical or admin side. If we break the usability and user-friendliness, this will be more harmful than a bad password.

A magic link to authenticate rises several questions:

1. What do I do if someone obtains this link?
2. Are you sure that an user will keep this link in his/her secure e-mail account? I doubt this. This link will be saved in bookmark lists of the browser, in some cloud, an insecure text editor, whatever.
3. What about the strong inconvenience to get this link if you wanna log in? Not everybody has her/his e-mail account linked with his smartphone nor keeps an e-mail client on his/her PC open always.
4. What if the link get's bruteforced?
5. What about Phishing?
6. What about browser history?
7. What if access to the mail account is lost?
8. Is it possible to disable this magic link option?

I think a password is still the one and only feasible solution nowadays. If you want to make it more secure, I suggest:

1. Providing 2-Factor-Authentification (SMS)
2. Implementation of HaveIBeenPwned
3. Implementation of basic password rules (minimum length, one digit or special char, etc.)

Getting one or all of these suggestions realized will improve the security of FROIDE a lot and doesn't break the usability. This are common solutions for more important sites and in my point of view way less annoying than a link I have to copy and paste from my mail box all time.

**Comment by rugk** [comment]
This issue is really getting off-topic, here...
So please: 2FA is a different issue. Please open it, if you want to see it. Same with HaveIbeenPwned for password rules. These are partially good ideas,, but all seperate issues. 
This issue is about **not sending passwords to users**!

IMHO also this "passwordless login" is off-topic, but as it could be a solution (which I don't like), I think discussion it here is okay.

But back to the topic...

----

> Can you point us to something to support the passwordless is insecure claim?

That was my personal evaluation, and it's easy to follow, if you think about it...
However, [I've written about this already, here, e.g.](https://discourse.mozilla.org/t/allow-usual-mail-password-login/18192), so I do not want to duplicate the information.

> I would think it moves security to your email account which a user might protect better (and likely has more security resources) than some random website.

1. Yes, it does.
2. But no, not better protected, or it does not matter.

Basically you always have this "email account fallback" will "password restore" options. As such, the baseline security (or "weakness", depends on how you see it) is always your mail account.
Or in other words: The "passwordless login" is a constant password reset, on each login.

The difference is just, that you will notice it if your password is reset, i.e. you notice a password breach. That's also the big argument for this issue - even if an attacker can intercept a password reset link, they cannot silently log in and read your data. In contrast to, if they compromise your mail account or intercept the sent password.

And when the random website is not properly protected (i.e. e.g. allows some authentication bypass) your mail auth/security won't help you neither.

So what is certain is, that it is less secure than a usual mail+password login. Whether to introduce it as an optional feature is your decicion.

**Comment by Ryuno-Ki** [comment]
@rugk wrote
> This issue is really getting off-topic, here...

GitHub offers a way to flag comments as off-topic, which will collapse them.

Regarding sending passwords per mail:
As long as it's an OTP I wouldn't mind.

**Comment by rugk** [comment]
> As long as it's an OTP I wouldn't mind.

But if you can only use it once, that is bad usability then. Because it requires users to copy and paste the one-time password. So you can again just use a link for that, which you can only click once.

**Comment by stefanw** [comment]
Fixed in 76995c6b74dd660968e02659cf30ba6d38666099
