### ISSUE TITLE
Problem report gets overriden, when using the same probelm category [German]

### ISSUE THREAD

**Issue by BjarneRest** [okfde/froide#267]
Hey,

wenn ich ein Problem mit einer Nachricht melde und es unter genau der gleichen Kategorie schon eine Problemmeldung gab, welche eventuell auch schon abgearbeitet wurde, wird nur der Problemtext überschrieben.

Beispiel:
Ich -> melde Problem der Kategorie "Ich brauche Hilfe die Nachricht zu verstehen". Das Problem wird daraufhin nach Bearbeitung als abgeschlossen/gelöst markiert.

Wenn ich jetzt erneut zur gleichen Nachricht (etwa als Rückfrage) ein Problem der gleichen Kartegorie melde, wird einfach der Text von der vorherigen Anfrage ersetzt. Der Status bleib jedoch bei abgeschlossen/gelöst. Somit kümmert sich keiner um das neue Problem.

Vielen Dank ;)

**Comment by arnese** [comment]
Moin! Ich bin mir nicht sicher, ob das ein Problem ist. Was für eine Änderung würdest du vorschlagen?

**Comment by arnese** [comment]
Scheint kein großes Problem zu sein.
