### ISSUE TITLE
Wrong Status „completed“ - add an „Report wrong data“ 

### ISSUE THREAD

**Issue by muescha** [okfde/froide#268]
Where:
- i see the topf secret map and point to an green pin
Or
- i use the FdS app and filter for completed

What i see
- i see a number of wrong requests with the status completed
  a) some of then when the request is send 
  b) some when there is an answer that the requester get it via letter, but no letter is uploaded

What i expect:
a) at first an button to report this wrong status
b) some more functions to avoid this wrong status
c) maybe an rewording is better because „anfrage erfolgreich“ some people only think this is when my request gets accepted but not when its full completed with all the requested documents
d) there should be a „change stats review“ possible before it goes to an „completed“ status

**Comment by arnese** [comment]
Moved to #308
