### ISSUE TITLE
send-message fails

### ISSUE THREAD

**Issue by k4l0ph41n** [okfde/froide#269]
send/message/#write-message fails sometimes (i.e.: can't send messages in any requests for hours, regardless of number of re-tries; some hours later, messages send fine and on 1st try). 

Tried on Firefox, Safari, regardless of mode (custom reply; template reply, or new message)

Expected: "Nachricht an Behörde senden" sends mail and confirms so on next page.

Instead: Page seems to reload, no sent mail, no confirmation, no error message.

**Comment by k4l0ph41n** [comment]
A few hours later, the "Sie haben 30 Anfragen / Woche überschritten" error message is now displayed. It appears this somehow prohibits replies (#write-message) in already existing FOI requests.

**Comment by stefanw** [comment]
We just fixed the error message. There's message throttling enabled. Please contact site support if this should not apply to you.

**Comment by k4l0ph41n** [comment]
Thanks - but this seems to mean that message throttling not only applies to new requests, but also to messages sent as replies to incoming mails in existing requests. So if a user is message-throttled, they can't reply to incoming mails until they drop below the request limit?

**Comment by stefanw** [comment]
We want to avoid that users send lots of messages in a short time without some supervision or approval. Maybe there should be different throttles for requests and messages. We plan to re-adjust our throttling logic soon.
