### ISSUE TITLE
Redaction in incoming email subject needed

### ISSUE THREAD

**Issue by k4l0ph41n** [okfde/froide#270]
Incoming emails can contain sensitive data in the email subject, e.g. Reply_LastName_FirstName_Date. The email subject is always public, and it can't be redacted by users.

Either automatically detect and redact names - or allow users to blacken email subject?

**Comment by arnese** [comment]
See: https://fragdenstaat.de/anfrage/auswirkungen-des-klimawandels-im-aufgabenbereich-ihres-ministeriums-2/#nachricht-156415
