### ISSUE TITLE
How to fetch a list of requests I follow

### ISSUE THREAD

**Issue by jfilter** [okfde/froide#272]
This endpoint <https://fragdenstaat.de/api/v1/following/> returns a list of URLs for requests I follow. Do I have to send one GET request for each request? Or can I just fetch them all similar to <https://fragdenstaat.de/api/v1/request/>?

**Comment by jfilter** [comment]
And a related question: How do I get the number of followers for <https://fragdenstaat.de/api/v1/request/>. Should I again send individual requests?

No problem for me. The number of mobile app users is alltogether <2k. I am not sure whether this affects the backend.

**Comment by stefanw** [comment]
New filter on request API:
```
https://fragdenstaat.de/api/v1/request/?follower=<userid>
```

`<userid>` must be the user id of the request's authenticated user and OAuth access requires `read:request` scope.
