### ISSUE TITLE
Reiter Kampagnen/Aktionen

### ISSUE THREAD

**Issue by Ameinsenbaer** [okfde/froide#275]
Wenn man nach bestimmten Kampagnen oder Aktionen sucht, muss man erst umständlich den Blog-Post suchen. Dagegen hilft ein Reiter mit der Aufschrift Kampagnen/Aktionen, der zB zwischen "Über uns" und "Blog" angezeigt wird, der auf eine Übersicht verweist.

**Comment by arnese** [comment]
Es gibt im Footer unter "Über uns" die Seite ["Unsere Kampagnen"](https://fragdenstaat.de/info/ueber/kampagnen/)

**Comment by Ameinsenbaer** [comment]
Könnte man dann dort auch Sache wie die IFG-Meisterschaften oder die zB die Aktion zu Handlungsanweisungen verlinken?

**Comment by arnese** [comment]
Done: https://fragdenstaat.de/info/ueber/kampagnen/
