### ISSUE TITLE
Support for extending the deadline

### ISSUE THREAD

**Issue by torfsen** [okfde/froide#281]
In one of my information requests, the government agency has extended the deadline (in a way allowed by the law) -- now FragDenStaat has reminded me that the original deadline has passed. What I'd like to do in cases like this is to manually change the deadline so that the request is only marked as delayed (and a notification is sent) when the extended deadline has passed (and not when the original deadline has).

**Comment by stefanw** [comment]
There should be a deadline extension form on the right side of your request.

**Comment by torfsen** [comment]
Ah, there is one indeed! However, it only became visible once I selected "Anfrage" in the left menu, the default for a request that has passed the deadline seems to be "Nachricht schreiben" with a pre-formulated reply asking for information about the state of the request. Hence I couldn't find it.

I will close this ticket since the feature is there, but I do suggest to make it more visible. For example, a link to the extension form could be included in the following places:

- After the text "Ihre Anfrage ist verspätet. Sie sollten der Behörde eine Nachricht schicken." that is displayed by default for delayed requests.
- As part of the "Status festlegen" form
- As part of the sections "Status dieser Anfrage" and "Frist" in the dashboard shown when "Anfrage" is selected on the left.
