### ISSUE TITLE
include public body's special notice to the request process 

### ISSUE THREAD

**Issue by jfilter** [okfde/froide#282]
There are about two request per day to the Hauptzollamt Frankfurt about personal belongings. People don't get the platform. So add the special notice when people write the request - not only to the public body page (actually, it's not important there and can be removed). And make it so people cannot miss it. i.e. red border.

The non-FOIA requests are annoying and people reveal very personal information.

![Screen Shot 2019-03-17 at 16 02 26](https://user-images.githubusercontent.com/3450307/54493323-ed1bdd80-48ce-11e9-8a8a-f67bfb5678c3.png)

**Comment by jfilter** [comment]
Or create an additional dialogue and ask a multiple choice question about FOI to ensure people really understand what's all about.

"Please mark all stuff one can request:
1. parcels [ ]
2. internal e-mails [x]
3. internal documents [x]
4. how much taxes do I have to pay? [ ]"

**Comment by GiantCrocodile** [comment]
I disagree with the dialogue option because it will be difficult to answer correctly for inexperienced persons. For example rarely anybody know that emails is fine.

**Comment by jfilter** [comment]
After the incorrect answer, the requester gets more chances to complete her or his request. Also an explanation should be given why an answer is correct or incorrect. However, let's start with a simple notice. :D

**Comment by stefanw** [comment]
There was a bug which was not showing the public bodies request hint.

https://fragdenstaat.de/anfrage-stellen/an/hauptzollamt-frankfurt-am-main-flughafen/
