### ISSUE TITLE
Unterstützung für HTTP 451

### ISSUE THREAD

**Issue by lobeck** [okfde/froide#284]
Anfragen bzw. Dokumente können aus rechtlichen Gründen gesperrt werden (z.b. die Glyphosat Stellungnahme). Dies sorgt aktuell für den Fehler:

`403 - Verboten
Sie haben versucht einen Teil der Seite aufzurufen, für den Sie keine Rechte haben oder Sie haben einen zusätzlichen Sicherheitsmechanismus ausgelöst.`

Hier sollte stattdessen der eigentlich richtige HTTP 451 verwendet werden (https://en.wikipedia.org/wiki/HTTP_451). Wodurch in solchen fällen auch eindeutig klar ist, warum ein Dokument nicht verfügbar ist. Zusätzlich könnte eine Verlinkung auf relevante Seiten wie z.b. Blog Beiträge über Hintergründe angeboten werden.

**Comment by stefanw** [comment]
Welche URL meinst du denn?

**Comment by lobeck** [comment]
`Ich verweise auf eine Anfrage auf FragDenStaat, der Sie Zugang zu den angefragten Dokumenten gewährt haben: https://fragdenstaat.de/a/63147 `

Das war eben noch ein 403. Habe auch gerade auf twitter gesehen, das ihr den 451 schon eingebaut habt 👍

**Comment by stefanw** [comment]
Die Anfrage war eben noch nicht öffentlich, jetzt aber schon. Den 451 Status haben wir auf das Dokument selbst gelegt. Danke für den Hinweis!

**Comment by lobeck** [comment]
Genau, das lief parallel zu diesem Issue. 

Der 451 klingt allerdings aktuell nach einem Hack und man sieht ihn leider nicht, wenn man die genaue URL nicht hat. Daher sehe ich das immer noch als ein Feature, das die Plattform bieten könnte. So könnten Dokumente intern geflaggt werden, der Fehler erscheint öffentlichkeitswirksam und ihr müsst z.b. nicht auf dem Webserver rumpatchen.
