### ISSUE TITLE
Postadresse wird mitgeschickt, auch wenn man das entsprechende Feld leert

### ISSUE THREAD

**Issue by markuspoerschke** [okfde/froide#286]
Schreibt man eine neue Nachricht an eine Behörde, so wird das Feld "Postadresse" mit den Daten aus dem Profil befüllt. Leert man den Inhalt des Feldes und sendet dann die Nachricht, so wird die Adresse aus dem Profil an die Nachricht angehangen. Der gewünschte Effekt wäre eigentlich gewesen, dass keine Adresse angehangen wird.

**Comment by stefanw** [comment]
Manche Behörden bzw. Gesetze benötigen eine Postadresse. Wenn keine Postadresse benötigt wird, wird eine Checkbox angezeigt, um die Adresse doch optional mitzusenden.

Wenn eine Postadresse benötigt wird, dann war bisher das Adressfeld fälschlicherweise nicht als "required" markiert und so konnte man es leer lassen. Das ist jetzt behoben.

Die Gefahr besteht jetzt, dass Leute etwas eintragen müssen, aber nicht wollen und den Wert auf "-" o.ä. setzen. Dieser Wert wird auch gespeichert und als künftige Adresse übernommen. Deswegen bieten wir aber bei jedem Nachrichtenversand an, die Adresse anzupassen.

**Comment by markuspoerschke** [comment]
Jetzt steht da zwar das "*" (Sternchen) für Optional, jedoch steht dadrunter ein nicht passender Text: „Optional. Ihre Adresse wird nicht öffentlich angezeigt werden.“.

**Comment by stefanw** [comment]
Wir erzwingen gerade eine Postadresse beim Bundes-IFG, da sich viele Bundesbehörden (z.B. BMI) momentan weigern, direkt an die FdS-Adresse zu antworten und immer eine Postadresse wollen. Wir arbeiten an einem Plan. Ggf. werden wir die Einstellung von Gesetzesebene auf Behördenebene verschieben.

Das Sternchen deutet verpflichtende Felder an, im Hilfetext  wurde das "Optional" entfernt.

**Comment by markuspoerschke** [comment]
> Wir erzwingen gerade eine Postadresse beim Bundes-IFG, da sich viele Bundesbehörden (z.B. BMI) momentan weigern, direkt an die FdS-Adresse zu antworten und immer eine Postadresse wollen.

Das Problem hatte ich mit einer Anfrage ebenfalls. Eigentlich wollte ich bei der Behörde auch darauf bestehen, dass ich meine Adresse nicht herausgebe. Das hat sich jetzt erübrigt ;) Bei meiner Anfrage handelt es sich um eine Kommunalverwaltung. Da würde dann natürlich die Unterscheidung IFG (Bund) und IFG (Land) sinnvoll sein.

Danke für die Infos! 👍
