### ISSUE TITLE
[security] Request can be found as public pdf (including private data)

### ISSUE THREAD

**Issue by k4l0ph41n** [okfde/froide#289]
The request submitted here 

https://fragdenstaat.de/anfrage/kommunikation-interministerielle-arbeitsgruppe-anpassung-4/

seems to be publicly available as pdf:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjx5peQ-u_hAhXNI1AKHSU_CrwQFjAAegQIBBAC&url=https%3A%2F%2Ffragdenstaat.de%2Fanfrage%2Fkommunikation-interministerielle-arbeitsgruppe-anpassung-4%2Fpdf%2F&usg=AOvVaw2dNPOSm4Pt2nt1MZDV-VYx

Same here: 

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=2ahUKEwjx5peQ-u_hAhXNI1AKHSU_CrwQFjABegQIBRAC&url=https%3A%2F%2Ffragdenstaat.de%2Fanfrage%2Fkommunikation-interministerielle-arbeitsgruppe-anpassung-9%2Fpdf%2F&usg=AOvVaw3eFkm9KbdIKr76s1XxwGAj

and here:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=2ahUKEwjx5peQ-u_hAhXNI1AKHSU_CrwQFjACegQIAxAC&url=https%3A%2F%2Ffragdenstaat.de%2Fanfrage%2Fkommunikation-interministerielle-arbeitsgruppe-anpassung-5%2Fdownload%2F&usg=AOvVaw3yA3Ts_8ys0bMeAJFPqPab

Those should not be public, they contain private data (!).

**Comment by k4l0ph41n** [comment]
In other words:

apparently [request-url]/pdf is sometimes not private.

Example: I can create 

https://fragdenstaat.de/anfrage/kommunikation-interministerielle-arbeitsgruppe-anpassung-4/pdf

without login.

**Comment by stefanw** [comment]
Thanks for spotting this and notifying us. It has been fixed in 8e9df53ae34f10ed0b034a6cb53b72d3477b4ac8 and deployed. Only 'project' requests were affected with only a limited amount of users. Nevertheless not good. I'm looking into removing URLs from the Google cache.

Please notify us privately via email next time regarding security issues.

**Comment by stefanw** [comment]
I triggered a cache and index removal of all affected URLs. In the mean time I also removed the Google cache link in the issue description.

**Comment by stefanw** [comment]
The Google index and cache removal seems to be complete. Beginning of next week we will involve our [external privacy officer](https://fragdenstaat.de/datenschutzerklaerung/) and then notify affected users.
