### ISSUE TITLE
Resend "Awaiting user confirmation" email

### ISSUE THREAD

**Issue by joernheissler** [okfde/froide#290]
Hi,
I tried to send a "Topf Secret" request and it looks like I had to receive an email and confirm the request.
Unfortunately, the email was lost (my mistake) and now the request is stuck in "Awaiting user confirmation" status. I can't delete it. I can't send a new request.

Could you please implement a feature to resend those mails?

**Comment by stefanw** [comment]
We can resend the activation email if you contact support. 

Implementing a user interface for self-service is tricky. Currently we do not keep track how often we send an email. How would you expect this to work?

**Comment by joernheissler** [comment]
I know too little about how the platform works.
My account is activated (see below for steps) and I could send other requests. But that one request is still in a bad state.
Perhaps there are better approaches to fix that bug than resending an email.

Reproduce:
* Ensure you're not logged into any account and all cookies are deleted.
* visit https://fragdenstaat.de/kampagnen/lebensmittelkontrolle/
* Request a report from any restaurant
* Webpage asks you to check your mails and confirm the address. Pretend the mail didn't arrive.
* go to https://fragdenstaat.de/account/login/
* register a new account with the same data
* webpage tells you to check your mails and confirm the address.
* click the confirm link from that mail and set a password
* You're then logged in and can the request. But it's not accessible, deletable, etc.

**Comment by joernheissler** [comment]
> if you contact support

I wasn't aware there was support available. Where/how?

**Comment by stefanw** [comment]
> I wasn't aware there was support available. Where/how?

Please mail us at: `info [at] fragdenstaat.de`

**Comment by stefanw** [comment]
I can confirm this behaviour. We are only sending the last request made by that account.

Someone could have made a pending request using your email address that you ignored. When you make an account, you don't want older requests that you may not have initiated to be sent. We also delete pending requests and accounts after 30 days. If you manage to stay in that timeline you see the older pending requests.

This is an edge case, but you are right: there should be an option to send or delete. I'm testing a solution now.

**Comment by stefanw** [comment]
There should be buttons on the request now that give you the choice of either deletion or sending.

**Comment by joernheissler** [comment]
Thanks, that solved my problem.
I deleted my request and I was able to create a new one.
But the deleted request is still lingering in the system:
GUI tells me that I've got 4 requests open, but I can only see 3 of them.
