### ISSUE TITLE
Delete "protected" original files

### ISSUE THREAD

**Issue by rugk** [okfde/froide#292]
If you have already censored your files and your case is closed, there is IMHO often no reason to keep the original files still on the server.
This just wastes space and contains personal information… so better delete it, if one does not need it anymore. :wink: 

Ref previous discussion: https://forum.okfn.de/t/kann-man-das-geschuetztes-original-loeschen/96?u=rugk

**Comment by duracell** [comment]
I think the GDPR should be respected and only information which are really needed should be saved, at least the use should have a option to delete this files.
If there is a leak the impact is much higher and could put the user and okf in problems, if there are private information (and a name could be enough) published. I don't see a "possible" later use in a lawsuit as a good reason. The user and the authority should have a physical or digital copy.

**Comment by jfilter** [comment]
> I don't see a "possible" later use in a lawsuit as a good reason. The user and the authority should have a physical or digital copy.

FragDenStaat is also an archive and other users should be able to see the documents as well.

Nevertheless, users should be able to delete documents for whatever reasons (#GDPR).

**Comment by rugk** [comment]
> FragDenStaat is also an archive and other users should be able to see the documents as well.

Public documents, only, however. This here is, however, only about private ("protected") files that are not visible to the public, anyway.

**Comment by stefanw** [comment]
When you delete your account, your non-public files are deleted. Please don't insinuate that we are not respecting GDPR.

The attachment/document management interface is complex, has many conditions and actions. It needs serious rework to encompass more features. This feature is being considered for inclusion.

**Comment by muibusan** [comment]
> The attachment/document management interface is complex, has many conditions and actions. It needs serious rework to encompass more features. This feature is being considered for inclusion.

Thank you very much. This feature would be greatly appreciated and also makes sense. :)

**Comment by rugk** [comment]
Has this been closed, because it's implemented or why?

Please note that it is best practice to comment on issues when they are closed to provide a reason. Alternatively, you can do so by closing an issue [from a PR or commit](https://help.github.com/articles/closing-issues-via-commit-messages/), which links them and thus also achieves the aim of providing an explanation of why an issue has been closed.
