### ISSUE TITLE
Send an email after you suggested a new public body/View public body suggestions

### ISSUE THREAD

**Issue by intrigus** [okfde/froide#298]
It would be great if you could send an email, each time you have suggested a new public body.
Because currently there is no way (At least no way that I know) to know which public bodies you already suggested.

Additionally it would be good to list all pubic bodies that the user suggested.

**Comment by arnese** [comment]
Since we are on par with working on these suggestions now (we included it into the moderation tool worked on by volunteers), this doesn't seem to be necessary anymore.
