### ISSUE TITLE
delete teams

### ISSUE THREAD

**Issue by eest9** [okfde/froide#299]
atm there is no option to delete teams. I created a team at http://fragdenstaat.at/ for testing reasons and now i can't delete it. Would be great if team owners could delete teams

**Comment by stefanw** [comment]
When you're the owner, at the bottom of the team page there's a delete button.

**Comment by eest9** [comment]
No, there isn't
![Bildschirmfoto von 2019-06-03 17-55-16](https://user-images.githubusercontent.com/11019106/58816015-ef1d4f00-8628-11e9-9b09-4aa8725c35e7.png)

**Comment by stefanw** [comment]
Yes, [there is.](https://github.com/okfde/froide/blob/master/froide/team/templates/team/team_detail.html#L183-L229)

But not in the deployment you're looking at. Ask @fin to pull.

**Comment by fin** [comment]
thank you for the feature request.
please report fragdenstaat.at bugs at https://github.com/fin/fragdenstaat.at/issues (:

**Comment by eest9** [comment]
Okay, sorry. 🙃
