### ISSUE TITLE
Voting for the most explosive inquiry

### ISSUE THREAD

**Issue by jvm123** [okfde/froide#3]
Open up the possibility for users to vote for the political relevance of an inquiry. I suggest to implement this with a 1-5 star system.
A seperate page -- or maybe even the front page --- could show the most "explosive" inquiries of the last n days; n should be configurable, so the user can choose between "top inquiries of the last 7/30/inf days". Also the user should be able to filter by (un)answered inquiries.

The voting is completely unrelated from following.

**Comment by arnese** [comment]
We have looked into this after 10 years. But it seems that a voting system does not make sense as it would amplify requests that are not necessarily useful and would lead to polarisation rather than useful filters. However, better filters for useful requests would be needed.
