### ISSUE TITLE
wrong repo, my mistake

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/froide#301]
nevermind

**Comment by GiantCrocodile** [comment]
@stefanw Can you delete this issue? I've created this issue at the wrong repository because of a browser caching bug ... thanks!

**Comment by stefanw** [comment]
Issues can't be deleted on GitHub.

**Comment by jfilter** [comment]
You should be able to delete an issue

![Screen Shot 2019-06-07 at 09 51 54](https://user-images.githubusercontent.com/3450307/59089294-0babd680-890a-11e9-9788-dd1fdfcdde65.png)

**Comment by stefanw** [comment]
A bit more complicated:
https://help.github.com/en/articles/deleting-an-issue

https://help.github.com/en/articles/allowing-people-to-delete-issues-in-your-organization
