### ISSUE TITLE
dependency version mismatch?

### ISSUE THREAD

**Issue by fin** [okfde/froide#302]
Installing requirements.txt leads to the following error:

`ERROR: celery 4.2.1 has requirement billiard<3.6.0,>=3.5.0.2, but you'll have billiard 3.6.0.0 which is incompatible.`

It doesn't seem to actively break anything, since tests are still passing [1], but I assume it should still be resolved

[1] https://travis-ci.org/okfde/froide/jobs/541796486

**Comment by stefanw** [comment]
Fixed it in master. There were some problems with some Celery version and our database configuration in the past [4878](https://github.com/celery/celery/issues/4878) [5483](https://github.com/celery/celery/issues/5483) that required some quick version changing where this got left in an incompatible state.
