### ISSUE TITLE
Twitter Handles are recognized as Email

### ISSUE THREAD

**Issue by schiederme** [okfde/froide#303]
Hey there,
If I put an Twitter Handles (e.g. @fragdenstaat) in the inquiry, it will be shown as "<<E-Mail-Adresse>>".

To recreate this bug, just create an inquiry and put an Twitter Handle somewhere.

To see it in wild, have a look at 151925 (IFG inquiry)

I hope this issue report is useful.

**Comment by stefanw** [comment]
Thanks for reporting this. Syntax for email addresses are complicated. This got triggered because a non-whitespace character was in front of the `@` (a double quote `"`). Regex has been improved.
