### ISSUE TITLE
Clean too many empty lines at the end of emails 

### ISSUE THREAD

**Issue by robbi5** [okfde/froide#304]
Current example: https://fragdenstaat.de/anfrage/quellcode-des-wahl-o-mat-server-variante/#nachricht-380946

Especially the bpb likes to add a whole lot of empty lines to the end of their emails.

**Comment by stefanw** [comment]
Fixed in 9bb72b62811eef0a94576648113e8f1e31262cce.

Thunderbird and Mail.app both strip the lines, but I don't get the rules around it. I'm leaving a max of three newlines in body text now.
