### ISSUE TITLE
Show receiver in team requests

### ISSUE THREAD

**Issue by rugk** [okfde/froide#306]
On the team page, when you do multiple (same) requests, which have the same title, to different receivers, you get a list of requests you can hardly differentiate.

After all, it just shows you the title and time of the request.

It would be good to extend this table, to at least show the receiver of an request.

**Comment by stefanw** [comment]
Please note that you should use project requests for identical requests to multiple authorities. They get their own project request view specifically for this use case and a separate table in the team view.

Making multiple same requests to different authorities without project requests is considered spam and may get you blocked.

More info here: https://fragdenstaat.de/plus/

**Comment by rugk** [comment]
Ugm, okay… did not know that.

**Comment by stefanw** [comment]
There's some spam detection that triggers automatically based on too many requests over time. We have to unblock accounts then, so the FdS+ way is the right way to go. Cheers!

**Comment by rugk** [comment]
Then detect same title on the projects page and recommend FdS+?

(However, I have to say, this could be considered like an advertisement feature.)

**Comment by arnese** [comment]
This does not seem to be a priority anymore.
