### ISSUE TITLE
Real name enforcement in comments

### ISSUE THREAD

**Issue by LukeLR** [okfde/froide#309]
When writing a comment on a request or an answer, the real name provided with the account is displayed publicly. Even if the option "hide my real name" was selected upon account creation, only a warning appears, that the real name will still be shown in comments.

Real name enforcment is highly discussed and rejected in internet communities. I don't know any portal which requires me to display my full name next to a comment. Every website allows the usage of usernames.

Why is it enforced here? I don't want my real name to appear on the internet, especially with political information as on fragdenstaat.de.

Enforcing the display of real names renders the comment function unusable for me. I'd like to see an option to choose an username for the comment function.

If that's not desirable from your point of view, please explain why.

**Comment by rugk** [comment]
Yeah, it's pretty useless to allow non-"real" names on requests, but then actually disallow them on comments.

I mean, you can in most cases very likely find out, who of the (possibly only one) ones that left a comment on a request is actually the one, who did the request.

So basically if you want to stay anonymous, your only choice is _not_ to comment your own requests – which is of course pretty crazy, as you very likely may want to say something about the repliesyou got, but you can't…

BTW pseudonymity for (the public view of) comments (and requests) would be fine, too. So you know, who answered to whom/what/…. but the current "real name policy" effectively destroys/undermines the whole feature of anonymous FOI requests.

**Comment by rugk** [comment]
Oh, awesome this has been fixed (so fast)! 🎉 Thanks. 👍 😃

**Comment by LukeLR** [comment]
Awesome! That was fast! Can't wait to See this in production :)

**Comment by stefanw** [comment]
To be clear: requesters with private accounts can now comment as "requester" on their own requests. For other requests there's currently still the clear name policy. We are hiring a community person that will also work on a more encompassing strategy.
