### ISSUE TITLE
Make setting "used law" more prominent

### ISSUE THREAD

**Issue by rugk** [okfde/froide#311]
There is a setting to set what law has been used by the agency:

![grafik](https://user-images.githubusercontent.com/11966684/60613407-20757000-9dcb-11e9-8938-41b6353dc38c.png)

However, when one does not look for it, one hardly discovers it.
And I guess, you may get some statistics by setting this (i.e. this is your intention for that feature).

---

Proposed solution: Maybe – when a FOI request has been resolved/answered successfully – you can show a message to the user like "Nice to see this has been resolved. You can additionally [set what law has been used for answering this](), if it is obvious to you."?

**Comment by arnese** [comment]
Since usually this is not possible for users to determine, we are planning to erase this feature in the upcoming relaunch.
