### ISSUE TITLE
Smaller values/moe flexible setting for extending deadline

### ISSUE THREAD

**Issue by rugk** [okfde/froide#312]
There is support for extending the deadline (see also https://github.com/okfde/froide/issues/281, which also has some other suggestions you may still look into), but that only works for months. (you also cannot input non-integer, i.e. float values like 0.25 months there)

But requests to EU agencies can be extended for (only) 15 working days (multiple times). So you literally cannot correctly extend it for

Alternatively, you may also just us a date picker (aka `<input type="date"`), because often the agency may also calculate the date a little differently (received Monday instead of Friday 22:00 or so, e.g.), and they tell me the date where it ends, so I can enter it directly.

**Comment by intrigus** [comment]
You can extend the deadline for eu agencies by 15 months.
This internally adjusts the deadline correctly by 15 working days.

**Comment by rugk** [comment]
Wtf...? Well, thats _very_ counterintuitive and a really bad UX. It says "months" there, not days... 🙄

**Comment by arnese** [comment]
@rugk, this is not the place for you to act this way. We want to cooperate on making Froide better. In order to help us doing this, please be polite. If you want to keep this tone, there are other places on the internet for you.

**Comment by silsha** [comment]
4c05267a5e596161ae3bae3a940aff01a199b17a broke the workaround by removing the input field. The button now adds +1 day to the deadline for EU agencies.

**Comment by rugk** [comment]
Sorry, did not want to sound inpolite, but my point was just: This is a bad usability (UX) and (without explanation) no user will ever discover this is possible. As such, this issue is valid and still needs to be fixed.

**Comment by stefanw** [comment]
To explain again: this was used by moderators only before. It clearly needs more attention to work for all kinds of users. The EU authorities have a different regime on deadlines that also needs to be calculated differently. This was not taken into account and the result is a bug.

I will disable the feature until it can be fixed.

**Comment by rugk** [comment]
I agree, but 
> I will disable the feature until it can be fixed.

is not good, IMHO. I mean, it basically works fine for German agencies. Quite...

**Comment by stefanw** [comment]
I see your point, but please understand that this tiny feature that is hardly needed or used by anyone has taken up too much time already. This becomes indistinguishable from bike shedding which I want to avoid.

**Comment by stefanw** [comment]
I reintroduced deadline extension in bd14d36e, it's now placed next to the deadline date. Amount can be varied between 1 and 15 and the unit of the law is shown.
