### ISSUE TITLE
Disable former public bodies

### ISSUE THREAD

**Issue by fin** [okfde/froide#313]
I have multiple public bodies that do not exist anymore, but requests to which can't be easily/automatically assigned to new ones. I could patch the codebase to add a new „allow new requests” field (default: true), unless you have a better solution?

**Comment by stefanw** [comment]
Currently we handle this by removing the email address. Without email address it will not show up in requestable authorities, but is still accessible anywhere else.

**Comment by fin** [comment]
That makes sense and I should have thought of it!
Thanks (:
