### ISSUE TITLE
Inconsistent law selection

### ISSUE THREAD

**Issue by basti-schr** [okfde/froide#314]
Different laws are used, depending on which way one takes to make an request.

Example with city of Chemnitz:
1. https://fragdenstaat.de/anfrage-stellen/an/stadt-chemnitz/
The Freedom of Information Statute is correctly chosen:
<img width="486" alt="fds-anfragean" src="https://user-images.githubusercontent.com/17143678/60904789-f4973600-a273-11e9-99bb-5be3bbc5358f.PNG">

2. Choosing Stadt Chemnitz via https://fragdenstaat.de/anfrage-stellen/?single
Only the SächsUIG/VIG is choosen.

<img width="491" alt="fds-neueanfrage" src="https://user-images.githubusercontent.com/17143678/60904925-463fc080-a274-11e9-85bd-3f444a4dd6cf.PNG">

**Comment by stefanw** [comment]
Looks like it works now, but unclear why. The question what is a jurisdiction is tricky. Chemnitz obviously should also reply to SächsUIG/VIG in addition to its local statute.
