### ISSUE TITLE
Attachments getting added seemingly randomly

### ISSUE THREAD

**Issue by intrigus** [okfde/froide#321]
https://fragdenstaat.de/anfrage/wd-8-10111-das-karlsruher-institut-fur-technologie-kit-1/#nachricht-407527

It says that there have been added 14 attachments.
But I only uploaded two attachments and redacted one of the two attachments.
So I effectively added three attachments and not 14.

I can't explain how this could have happened.

**Comment by arnese** [comment]
We made this feature invisible since it didn't seem to provide a lot of useful information.
