### ISSUE TITLE
Usability problems when redacting PDFs: wrong button clicked

### ISSUE THREAD

**Issue by rugk** [okfde/froide#328]
## Problem

When the PDF is not yet published, you see two buttons:

> [Apply redactions]                        [Publish without redactions]

The button at the right is green, which makes it appear like the "default" button. The left button to actually apply the reductions is black, though.

Thus I often click the wrong button after redacting all things I wanted to redact, because I just hit the green "okay, continue" button, thinking it is the correct one.

## Solution

Maybe make the apply button green/highlight it?
And make the "publish without redacting" button less visible?

Add a warning before discarding the redaction?

**Comment by stefanw** [comment]
The redact button is `black` (like your redaction) everywhere on the site. The green button is prominent, so people don't redact when there's nothing to redact. But I see your point.

**Comment by jfilter** [comment]
I just want to second, that I also often want to click on the wrong button. One option: Reduce the size/change color of the 'no redaction button' as soon as you redact once.
