### ISSUE TITLE
Calling the ombudsperson is not possible when the agency never answered

### ISSUE THREAD

**Issue by intrigus** [okfde/froide#333]
I'm trying to call the ombudsperson for this request: https://fragdenstaat.de/a/169904
(I'm calling the ombudsperson because Europol did not respond to **any** request so far)

I've tried to set the state to "request denied" ("Anfrage abgelehnt") then this happened:
![grafik](https://user-images.githubusercontent.com/10353467/68631617-bcd32000-04eb-11ea-8d9a-782526f151f5.png)

This helpfully suggests calling the ombudsperson but clicking the link - nothing happens.
I'm not sure whether this is specific to European agencies.

**Comment by stefanw** [comment]
The hint at the top has been removed.

The request you mentioned is not in a state that can be escalated to a mediating authority:
- it has not received a reply
- it is not overdue

**Comment by intrigus** [comment]
And how do I then solve my problem?
The address fds is using for Europol has not been responding to any previous request.
So I really have to wait 3 weeks to let my request become overdue despite knowing that I now already know that I will not get any answer?

**Comment by stefanw** [comment]
You can escalate a previously unanswered request that has become overdue. Clearly the ombudsperson should not react to a request you just made a couple of days ago just on the basis that you "know" that Europol is not going to respond.
