### ISSUE TITLE
Copy a request and make it yourself

### ISSUE THREAD

**Issue by CSDUMMI** [okfde/froide#334]
Sometimes the office to which a request was made, forbids the publication of the files on fragdenstaat.de - Regardless of whether this is legal or not - 
I'd like to introduce a feature, that let's you click a button on the page of the request in question, sending a new request with the exact same request text to the exact same office. Then, once the files have been transmitted to you, under the same condition, Froide checks the files against the SHA256 of the files of the original request and maybe, if enough people use this feature on a request, the office allows the publication of the file eventually.
An example of such a request would be:
https://fragdenstaat.de/a/168138

**Comment by stefanw** [comment]
This feature already exists, we have used it many times. See here for an active example: https://fragdenstaat.de/a/26322

We deduplicate files on storage via hash, but don't actively check if files are watermarked. We have not yet found a case of user-specific watermarks. Automating user-specific watermark detection (and communicating results to users) is currently out of scope. When we find the first example, it might become relevant.

**Comment by CSDUMMI** [comment]
How could one activate this? 
And who can do so?

**Comment by jfilter** [comment]
This can only be activated by admins to prevent abuse. Feel free to send an email to info@fragdenstaat.de if you need it. ;)
