### ISSUE TITLE
mismatching FOI request counts/no proper count anymore

### ISSUE THREAD

**Issue by juliuste** [okfde/froide#335]
There seems to be a mismatch between the total count of FOI requests displayed on the front page (first screenshot) and the search page (`/anfragen`) without any active filters (second screenshot).

Could it be that private requests are included in the front page stats while excluded in the search?

---

<img width="100%" alt="count on front page" src="https://user-images.githubusercontent.com/1584289/71560575-550d7000-2a6c-11ea-9e06-305356a34bb8.png">

---

<img width="100%" alt="count on search page" src="https://user-images.githubusercontent.com/1584289/71560578-68204000-2a6c-11ea-922f-0b0436960772.png">

---

**_edit_**: The numbers on public entities also don't match 😄 

<img width="100%" alt="entity count on search page" src="https://user-images.githubusercontent.com/1584289/71560832-e1209700-2a6e-11ea-9acf-3b6d49fe1a24.png">

**Comment by stefanw** [comment]
I fixed it by breaking it another way. The Elasticsearch upgrade resulted in a 'at least this many results' count, showing now always 10.000 'requests' or 'public authorities'.
