### ISSUE TITLE
Datenschutzbeauftragte falsche Kategorie

### ISSUE THREAD

**Issue by rugk** [okfde/froide#342]
https://fragdenstaat.de/behoerde/der-sachsische-datenschutzbeauftragte/
eingeordnet als: Inneres
sollte eingeordnet sein als: Beauftragte für Datenschutz und Informationsfreiheit

https://fragdenstaat.de/behoerde/die-landesbeauftragte-fur-den-datenschutz-und-fur-das-recht-auf-akteneinsicht/
eingeordnet als: Inneres
sollte eingeordnet sein als: Beauftragte für Datenschutz und Informationsfreiheit

https://fragdenstaat.de/behoerde/beauftragte-fur-datenschutz-und-informationsfreiheit-osnabrueck/
eingeordnet als: Beauftragte für Datenschutz und Informationsfreiheit
sollte eingeordnet sein als: Inneres
(Damit dies nicht mit den Landesdatenschutzbeauftragten vermischt wird – sonst würde es die Liste ja sehr sprengen von jeder Stadt etc. den/die Beauftragte aufzulisten)

https://fragdenstaat.de/behoerde/die-landesbeauftragte-fur-den-datenschutz-niedersachsen/
eingeordnet als: Inneres
sollte eingeordnet sein als: Beauftragte für Datenschutz und Informationsfreiheit

https://fragdenstaat.de/behoerde/unabhangiges-datenschutzzentrum-saarland/
eingeordnet als: Inneres
sollte eingeordnet sein als: Beauftragte für Datenschutz und Informationsfreiheit

https://fragdenstaat.de/behoerde/landesbeauftragter-fur-den-datenschutz-sachsen-anhalt/
eingeordnet als: Inneres
sollte eingeordnet sein als: Beauftragte für Datenschutz und Informationsfreiheit

https://fragdenstaat.de/behoerde/unabhangiges-landeszentrum-fur-datenschutz-schleswig-holstein/
eingeordnet als: Inneres
sollte eingeordnet sein als: Beauftragte für Datenschutz und Informationsfreiheit

Bei FdS Plus ist sind diese Behörden in der Auswahl zu "Beauftragte für Datenschutz und Informationsfreiheit" dann nicht zu sehen. Es sind nur 12 Behörden, statt 16 (Bundesländer) + 1 (Bund BfDI) gelistet, mit der oben erwähnten Falschkategorisierung.
Nach vorgeschlagener Kategorisierung hätte man alle Behörden gleichzeitig.

**Comment by stefanw** [comment]
Hallo, du verwechselst hier offenbar Klassifikation (Behördentyp) und Kategorie. Teile deiner Beispiel haben jeweils das eine oder das andere. Die Behördeneinordnung ist momentan leider immer noch ziemlich chaotisch.

Zur Erklärung: Wir haben zwei Arten eine Behörde einzuordnen: Behördentypen und Kategorien.
Jede Behörde hat 0 oder 1 Behördentypen und 0 oder mehr Kategorien. Behördentypen und Kategorien sind beide hierarchisch, dass heißt sie haben ggf. mehrere Unterkategorien/Untertypen oder eine Oberkategorien/Obertyp.

Beispiel wie es vermutlich sein sollte für die Beauftragten für Datenschutz und Informationsfreiheit der Länder
- Kategorien: Datenschutz und Informationsfreiheit (beides Unterkategorien ggf. von Inneres)
- Behördentyp: "Beauftragte für Datenschutz und Informationsfreiheit" als Untertyp von "Beauftragte"

Dazu kommt bei uns noch:
- Zuständigkeitsbereich, aus dem die standardmäßig anzuwendenden Gesetze hervorgehen
- die geographischen Regionen auf die sich die Zuständigkeit dieser Behörde erstreckt

Über die Hierarchie können wir dann Behördengruppen schnell zusammenfassen, einerseits nach ihrem Typ oder eben nach ihren Themenbereichen.

Die aktuellen Daten spiegeln das nicht überall wieder. Wir haben uns bisher darauf konzentriert, gewisse Behördentypen ordentlich und komplett abzubilden (z.B. Hygienekontrollbehörden). Wir arbeiten an einer Lösung, bei der auch die Community bei diesen Aufgaben mithelfen kann.

**Comment by rugk** [comment]
Okay, danke. Ich hatte mich v.a. auf das Problem bezogen, dass man bei FdS Plus nur einige Landesdatenschutzbehörden nach Auswählen des Typs(?) "Beauftragte für Datenschutz und Informationsfreiheit" sehen konnte.

**Comment by stefanw** [comment]
Ich habe etwas aufgeräumt, sollte jetzt besser sein.
