### ISSUE TITLE
Always auto-censor the special access link

### ISSUE THREAD

**Issue by rugk** [okfde/froide#344]
Case: *****

Here, the privacy protection agency sent the link back to the FOI requester, because they had a technical issue.
This led to the problem that this link is now publicly accessible.

___

Possibly do that for all the URL patterns of that kind.
Because when you e.g. include links to other requests [like here](https://fragdenstaat.de/anfrage/informationen-zum-kompetenzzentrum-open-source-software-cc-oss-2020/#nachricht-487729), they are also not automatically censored.

**Comment by arnese** [comment]
Please don't put these kinds of issues on Github but send us an email first. Thank you.

**Comment by rugk** [comment]
Oh IÄm stupid… yep…

**Comment by stefanw** [comment]
Before we only removed the secret URLs of the request in which the URL appeared. 078610ae954f74fa946584cd3aa0e73404e83841 makes sure to remove all patterns of these URLs.
