### ISSUE TITLE
Creating new a problem in a request in same category as previous problem does not create trackable issue

### ISSUE THREAD

**Issue by k4l0ph41n** [okfde/froide#345]
When a problem report has been created in a request message, e.g. on "Ich brauche Hilfe, um Nachricht zu verstehen" and already answered, creating a new problem in the same category apparently only adds to the existing problem, but does not create a new trackable issue ("problem" count remains unchanged + issue remains "solved"). Only if a new category is picked, a new issue is created (and problem count +1).

See e.g.

https://fragdenstaat.de/anfrage/interne-weisungen-dokumente-zum-umgang-mit-rassismus-222/#nachricht-499149

**Comment by arnese** [comment]
True. But to be fair, you should have put the new problem report to the corresponding message further down the request ;)

**Comment by k4l0ph41n** [comment]
True :) but does not change a potential problem :)

**Comment by arnese** [comment]
This has been fixed.
