### ISSUE TITLE
Enable changing addressee after adding a sent letter

### ISSUE THREAD

**Issue by teriky** [okfde/froide#352]
After adding a sent letter it is not possible to change the addressee.

For this reason a mistake while adding a scanned letter could not be fixed.

![addressee](https://user-images.githubusercontent.com/40558729/88680683-0eaaed00-d0f1-11ea-96bf-85b4638f4a31.png)

**Comment by stefanw** [comment]
Thanks, fixed in 11e3a7bbf2f88af2052250961aff7c0f216ee8ed.

**Comment by teriky** [comment]
Hi Stefan, thanks for enabling later addressee changes.

I suggest changing the button's text to "Ändere Empfänger-Behörde" (change addressee).

![froide](https://user-images.githubusercontent.com/40558729/94687319-643b8a00-032c-11eb-9d23-3dd013f2d789.jpg)
