### ISSUE TITLE
Format placeholder gets not applied

### ISSUE THREAD

**Issue by alehaa** [okfde/froide#353]
If a requested change of a public body gets approved, [the placeholder in the related subject line](https://github.com/okfde/froide/blob/47c0c41d08c6d7d2b7c8ad1dbb66e37fc4124a28/froide/publicbody/forms.py#L250) will not be substituted by the public body's name. The (German) subject line will be rendered as:
> Änderungen an Behörde „%s“ wurden vorgenommen

I tried to locate the bug. However, the specific code seems to use the `format()` function correctly. Maybe there could be an issue with [the German translation message](https://github.com/okfde/froide/blob/476ddcf33522ebc243f08045a09fc54c3754d0ee/locale/de/LC_MESSAGES/django.po#L8018), so the `format()` function doesn't get the required placeholder in the desired format?

**Comment by ZackDev** [comment]
The line causing the bug uses a mix of deprecated `%s` and the newer format method, which aren't compatible.
_Simply replace the current placeholder `"%s"` with `{}`, the resulting line should look like this:_
`_('Changes to public body {} have been applied').format(`

The old style would look like this:
`_('Changes to public body %s have been applied' % pb.name`

**Comment by stefanw** [comment]
Thanks, fixed it. (%-formatting is not deprecated).
