### ISSUE TITLE
Status festlegen: Behörde nicht zuständig

### ISSUE THREAD

**Issue by amigalemming** [okfde/froide#364]
Ich habe bei verschiedenen Anfragen die wahrscheinlich häufigste Beamtenantwort bekommen: "Nicht zuständig". Ja, in dem Standardanfragetext von FragDenStaat steht drin, dass bei Unzuständigkeit die Behörden weiterleiten sollen. Machen sie aber nicht. Könnte man bei "Status festlegen" noch den Grund "nicht zuständig" hinzufügen? Oder einen Tipp anzeigen, wie man mit diesem Fall umgehen soll? Wenn ich eine neue Anfrage starte, laufen ja die Fristen wieder von vorne.

**Comment by arnese** [comment]
Fehlende Zuständigkeit ist kein Ablehnungsgrund, damit auch kein sinnvoller Status. Es ist damit aber wohl gemeint, dass eine Info nicht vorliegt. Dafür gibt es den Status "Information nicht vorhanden", der in deinen Fällen verwendet werden sollte.
Technisch ist es eine neue Anfrage mit neuen Fristen, da kann man wohl nichts machen.

**Comment by amigalemming** [comment]
In manchen Fällen bin ich mir recht sicher, dass denen die Informationen vorliegen, aber sie sagen, dass sie nicht für die Prüfung der Anfrage und die Herausgabe der Informationen zuständig sind.

**Comment by arnese** [comment]
In dem Fall ist der richtige Status "Anfrage abgelehnt". Den Ablehnungsgrund kann man dann einstellen.
