### ISSUE TITLE
Mails are silently ignored

### ISSUE THREAD

**Issue by alehaa** [okfde/froide#365]
Froide seems to ignore emails sent to the address for a specific request silently, if the sending address is not whitelisted in some way. It neither sends a bounce message instead. In my opinion, the SMTP server should reject the mail in the first place instead, to inform the sender about this behavior.

Background: In some cases, a public body may require to submit information via a web form, i. e. to file a complaint about an ongoing request. While one can add this information as "letter send to the public body" manually, passing the request-specific email address should allow third parties to send their answer. Silently ignoring these mails may lead to false assumptions, that the mail has been received by Froide.

You can reproduce this by sending a test email to the request-specific email address, e.g. from your private account, which has no known domain of any public body:
```
Sep 27 23:27:42 v1y postfix/smtp[1966]: Trusted TLS connection established to mail.fragdenstaat.de[94.130.55.89]:25] TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange ECDHE (P-384) server-signature RSA-PSS (2048 bits) server-digest SHA256 
Sep 27 23:27:42 v1y postfix/smtp[1966]: 30F8A20195: to=<xxxxxxxxx@fragdenstaat.de>, relay=mail.fragdenstaat.de[94.130.55.89]:25], delay=0.41, delays=0.11/0.1/0.11/0.08, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as 7E097A40D6F)
Sep 27 23:27:42 v1y postfix/qmgr[4990]: 30F8A20195: removed
```

**Comment by arnese** [comment]
The e-mails you sent as tests as well as other possible spam show up in our moderation tool. I just classified them as spam so they got rejected. If we recognize them as legitimate answers, we can let them through.

**Comment by alehaa** [comment]
Okay, this seems legit. Will every mail be checked, or should one send a message to the moderation team if one uses the mail in an external form? I don't know how many mails a day show up in the moderation tool ...

**Comment by arnese** [comment]
We check all the mails individually or at least per sender, but it can't harm if you notify us via the problem button. In any case, we are not fans of the solution you are proposing and would be happy if you used the "letters sent" button manually for all correspondence you filed somewhere else.
