### ISSUE TITLE
JSONField type incompatible

### ISSUE THREAD

**Issue by alehaa** [okfde/froide#369]
[The documentation](https://github.com/okfde/froide/blob/master/docs/gettingstarted.rst) states, that PostgreSQL is the preferred database, but any Django-supported geospatial database may be able to use. However, by using `django.contrib.postgres.fields.jsonb.JSONField` as fixed datatype in several places of the Froide code, it is bound to PostgreSQL.

I would like to contribute an abstraction class as suggested in [this article](https://medium.com/@philamersune/using-postgresql-jsonfield-in-sqlite-95ad4ad2e5f1) to allow using Froide with SQLite. At the moment I can't find a central place where the ORM models are stored. Is there any fixed directory where such class should be stored?

**Comment by stefanw** [comment]
I'm sorry to tell you, that the documentation is out of date. Froide no longer supports multiple database backends (or multiple search backends for that matter), but is only tested on PostgreSQL.

If you really want to run froide with SQLite, there's hope yet: Django 3.1 (which we will upgrade to soon) has a [built-in JSONField support for all supported database backends.](https://docs.djangoproject.com/en/3.1/releases/3.1/#jsonfield-for-all-supported-database-backends) So after the upgrade and a bunch of migrations all JSONFields should work with SQLite.

However, this does not mean that we support SQLite. We may use HStore, Array and FTS index fields in the future (and already do in some extensions). Also we make use of geo features of Postgres that may or may not be available in SQLite.

**Comment by alehaa** [comment]
I tested running Froide with an abstraction class as suggested by the article and it seems to work pretty well.

My intention was to file a pull request to Froide and commit this change upstream to allow others to use it as well as needed. However, with the explicit note, that this is not the preferred configuration of the Froide maintainers and that there isn't any support for this feature (use at your own risk). E.g. nextcloud allows using SQLite for development, too, but always adds a big warning that this configuration should not be used for production and may be unstable.
