### ISSUE TITLE
Handle already publicly published energy certificates of buildings

### ISSUE THREAD

**Issue by teriky** [okfde/froide#372]
This request should handle the following use case regarding the "Klima-Gebäude-Check" campaign:

A city answers a request with or without the requested document AND provides an URI to publicly published energy certificates (e. g. [energiemanagement.stadt-frankfurt.de](https://energiemanagement.stadt-frankfurt.de/) below menu entry _Energieausweise_).

It doesn't make sense to send lots of requests for documents that are already public available.

One solution might be to (pre)assign those documents to buildings (and mark the as available). This is labor intense but enables automated analysis behind the scenes.

An easier solution might be to provide a banner with a hint for those cities like "Energieausweise für Gebäude von [Stadt] finden sie unter [URI]. Nur dort nicht vorhandene Energieausweise müssen angefragt werden." (energy certificates of [city] are available at [URI]. Only missed energy certificates need to be requested.).

Other solutions might make sense, too.

**Comment by arnese** [comment]
This campaign has been set to asleep, so we won't work on this.
