### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by rugk** [okfde/froide#373]
[Hacktoberfest 2020](https://hacktoberfest.digitalocean.com/) – a project promoting open source contributions – is running this month.

As [they have changed the rules recenty](https://dev.to/devteam/hacktoberfest-etiquette-for-contributors-ec6) you do now have to tag your repository/repositories (=set a GItHub topic) if you want to have participated in this with the tag `hacktoberfest`.
AFAIK you can alternatively also [tag single PRs with `hacktoberfest-accepted`](https://hacktoberfest.digitalocean.com/details#details) to mark them as a valid PR. (Otherwise all merged or positively reviewed PRs count.)

Could you do so, so one may send some PRs and participate there?

**Comment by thedudio** [comment]
I think it should be mentioned more often in general, that help is needed here. For example in the talks at ccc and others.
I watched a video of the ccc and @arnese mentioned this repo in the very last minutes of the video in the Q&A section.
https://www.youtube.com/watch?v=DrkGuzinqAY&ab_channel=media.ccc.de

**Comment by rugk** [comment]
Hacktoberfest is nearly over. 😢 
Could you still do so, so a PR counts? @jfilter @stefanw

**Comment by jfilter** [comment]
I don't have access to this repo. Maybe @arnese can help?

**Comment by rugk** [comment]
Oh you are listed as a "member" in the OKFN and even your comment shows you are a member of this repo, so I thought you could help here.

**Comment by rugk** [comment]
October is over and nobody from OKFN/FdS replied… 🙁
Thus, closing this. 😰

**Comment by alehaa** [comment]
Afaik PRs already submitted can still count for hacktoberfest, if tagged as `hacktoberfest-accepted` in the "review period" of 14 days.

**Comment by rugk** [comment]
Oh okay, did not know that. So re-opening…

Unfortunately, I do not have much hope that someone does sth. here as they ignored this for months and I don't know whether dropping a mail or so would help. (They should have got sth. through GitHub notifications anyway.)

**Comment by rugk** [comment]
Also note there [are not few PRs](https://github.com/okfde/froide/pulls?q=is%3Apr+is%3Aopen+created%3A2020-10) created during October, though I of course don't know whether they all participate in Hacktober, but well…

**Comment by arnese** [comment]
Hi! As I have stated in another repo already, we don't have enough resources at the moment to properly cater for this. I don't think it makes sense to call for contributions when we are not able to review them in a way that makes this a satisfactory process for all. I hope we can change this by early next year.

**Comment by rugk** [comment]
Well ok your decision, just saying [there are 4 small PRs to review](https://github.com/okfde/froide/pulls?q=is%3Apr+is%3Aopen+created%3A2020-10), which are not a lot. And if you now tag these PRs e.g. nobody new will come – Hacktoberfest is over.

Anyway, given that seems to be a decision, I'll close this issue. (For everyone else: the comment you seem to refer to before [seems to be this one](https://github.com/okfde/froide/issues/367#issuecomment-708598596).)
