### ISSUE TITLE
Delegate redaction-related problems to inquirer

### ISSUE THREAD

**Issue by alehaa** [okfde/froide#375]
In order to relieve moderators, problems concerning redaction could be directed to the inquirer first. If the requester does not react within a certain time, the problem would then be forwarded to moderators.

Although a (public) comment could also be made in the request, this doesn't remove the comment after resolving, nor does it allow automatic escalation.

**Comment by arnese** [comment]
This doesn't seem to be a big issue anymore. Both moderators and more redaction tools for inquirers seem to suffice.
