### ISSUE TITLE
Klima-Gebäude-Check, check request letter regarding which law is used

### ISSUE THREAD

**Issue by gislars** [okfde/froide#380]
Based on a response of Bezirksamt Pankow and a discussion in this [okfn forum thread](https://forum.okfn.de/t/antwort-mit-aufforderung-nach-ifg-anzufragen/1063) there might be an issue with the the text of the request letter. 
Within three request, three different texts are used. Also please check if references and mixed use of UIG and IFG might be misleading.  Within the forum thread it was suggested to use only UIG (or LandesUIG).

**Comment by arnese** [comment]
Hi! Thank you for the suggestion. It seems, though, that everyone is correct - the UIG are different vom Bundesland to Bundesland, so it makes sense if the texts differ. In Berlin, there is not UIG, so IFG is correct.
