### ISSUE TITLE
Show mail carbon copy (CC) field

### ISSUE THREAD

**Issue by rugk** [okfde/froide#382]
The [mail CC field](https://en.wikipedia.org/wiki/Carbon_copy#Email) shows if you were taked

Use cases may be:
* an agency redirects a request to someone else (another agency or internal) and sends the mail with yourself on CC
* an mediation request (agency/DPA or so) sends a mail asking for information to the agency you FOI-requested. They send a mail with yourself on CC.

Note: This issue is only about *showing* that field, not yet sending mails as CC: Although I think this is also useful IMHO, it would be better to create a new issue for that (and link to this one as a dependency).

See also: [forum thread on this topic](https://forum.okfn.de/t/anfrage-bei-uns-falsch-wir-leiten-weiter/1088?u=rugk).

**Comment by arnese** [comment]
The CC field is available to see now.
