### ISSUE TITLE
Add “notes for FragDenStaat” field to agency suggestions

### ISSUE THREAD

**Issue by rugk** [okfde/froide#391]
If you suggest an agency on https://fragdenstaat.de/behoerden/vorschlagen/ I would like to have one more field for **notes** or better “notes for FragDenStaat/staff/person in charge” or so.

This should:
* only be shown to FragDenStaat
* may be deleted if the agency is approved (or keep it for your records)

This would allow me to to explain the change I am doing or why I am doing it or why the new entry is valid.
E.g. why some GmbH or AG may still be a valid target for a FOI request, as they take public tasks. (cf. § 1 para. 1 sentence 3 IFG)

**Comment by arnese** [comment]
Closing similar issue in https://github.com/okfde/froide/issues/441
