### ISSUE TITLE
german translation: augment used version of gendering to include non-binary people

### ISSUE THREAD

**Issue by Unip0rn** [okfde/froide#397]
The current german translation uses a slash "/" to seperate a male associated and a female associated version of the same function of a person. This implies a choice from all *listed* options, thereby excluding non-binary people. To fix this I propose changing it to a colon ":", as it is much more naturally to follow with screen readers than an asterisk "*" since it is being read as just the short gap as intended in spoken language, but still is not associated with concluded lists of options. An example of the resulting language would be "Antifaschist:in"
Further I'd like to change the standard greeting subtly to "Sehr geehrte Damen bis Herren" (from currently Damen *und* Herren") to make clear that men and women are not the only genders to be observed while fitting nicely with language "flow" (I lack a better word here). This is however against a conception of gendering being supposed to point people to the fact that it is being actively augmented to include everyone and thereby pushing towards reflection of gender roles as percieved within society.

This issue is to start a discussion on the topic if needed and before starting the actual work see, if there are aspects I missed.

**Comment by arnese** [comment]
Hi Unip0rn! 
Thank you. We are using the colon option in our blog and support pages but we might have some spots on the website where we don't. Can you point me to one or two examples of this?

**Comment by Unip0rn** [comment]
fixed in #398 for fragdenstaat.de to the extent of my knowledge.

**Comment by Unip0rn** [comment]
#398 is not merged yet, however - if it is knowingly not handled yet is there an ETA or something? Sorry for bothering again.

**Comment by pajowu** [comment]
We decided to use "Guten Tag" instead of "Sehr geehrte Damen und Herren" now, so this issue shoud finally be fixed 🎉
