### ISSUE TITLE
Colored PDF only shown in grayscale and broken in request

### ISSUE THREAD

**Issue by rugk** [okfde/froide#401]
In a little embarrassing conversation I had to notice that the PDF the agency sent to me is disturbed:
The following _energy performance certificate_ is correctly shown to me in a local PDF viewer (Envince 3.38.0 on GNOME), b ut broken on the website:
https://fragdenstaat.de/anfrage/energiebedarfsausweis-fur-gebaude-landesbetrieb-information-und-technik-nordrhein-westfalen-mauerstrae-5-140476-dusseldorf/550050/anhang/WE2330Ausweis_2.pdf

I know you can do nothing here, and noticed it is actually an issue in PDF.js, so I've opened this issue:
https://github.com/mozilla/pdf.js/issues/12752

Just in case someone else has a similar issue or get the documents from the same agency (_Bau- und Liegenschaftsbetrieb NRW_), you now know what is causing this. And you can close this if upstream has fixed this issue and you've updated your platform.

**Comment by arnese** [comment]
Perspektivisch werden das sowieso alles Dokumente wie hier schon mal gemacht. https://fragdenstaat.de/dokumente/7996-we2330ausweis_2/

**Comment by rugk** [comment]
Ah danke! Das ist ja cool.

**Comment by alehaa** [comment]
[Hier](https://fragdenstaat.de/anfrage/energiebedarfsausweis-fur-gebaude-landesamt-fur-besoldung-und-versorgung-nrw-johannstrae-35-40476-dusseldorf/551017/anhang/Energiebedarfsausweis.pdf) habe ich dasselbe Problem, nach einem Download kann ich die Datei aber "normal" betrachten.

@arnese es wurde Upstream inzwischen [ein Patch bereitgestellt](https://github.com/mozilla/pdf.js/pull/12753). Könnt Ihr diesen ggf. auf FdS deployen?

**Comment by arnese** [comment]
@alehaa nächstes Jahr :)

**Comment by Ryuno-Ki** [comment]
Also dieses?

**Comment by stefanw** [comment]
I tried to upgrade to latest pdf.js viewer, but there are problems with our CSP disallowing `eval`. Feel free to make [latest pdf.js viewer](https://mozilla.github.io/pdf.js/web/viewer.html) work without eval and let me know how it goes.

**Comment by rugk** [comment]
How do you include it and what are the errors?
Because this seems to be a well-known error, see https://github.com/mozilla/pdf.js/issues/12105, actually https://github.com/mozilla/pdf.js/issues/11036, a downstream dependency of PDF.js seems to have an issue.

So [could you switch to](https://github.com/mozilla/pdf.js/issues/11036#issuecomment-586578418):
> A modern build (for up-to-date browsers), which is not transpiled with Babel and without any included polyfills.

---

That said, BTW, the last pdf.js release AFAIK does not include [the patch for this issue](https://github.com/mozilla/pdf.js/pull/12753) (look at the dates). It's not released yet.
That said, updating pdf.js never hurts, you need to do it anyway at some point.

**Comment by stefanw** [comment]
We can‘t use a version that breaks CSP or breaks older browser compat (older here means does not support things like optional chaining which is quite a few). We are using the viewer from pdf.js demo with some changes (no url validation, eval off, de locale, reduced toolbar): https://github.com/okfde/django-filingcabinet/tree/master/filingcabinet/static/filingcabinet/viewer

**Comment by alehaa** [comment]
Is there any update on this issue? I'm still observing it in some request answered by a specific authority.

**Comment by stefanw** [comment]
PDF.js has been updated to latest stable version. The mentioned PDFs are now rendering ok.

Where PDFs are just shown (via iframe) we are no longer using a bundled version of pdf.js but the native browser PDF viewer (which for Firefox is pdf.js). PDF.js is used to augment our document viewer, in the redaction process and for attachment previews in the message attachment manager.
