### ISSUE TITLE
Using (abusing) Froide for a reboot of isitopendata.org (discussion)

### ISSUE THREAD

**Issue by rufuspollock** [okfde/froide#41]
We used to run a service called http://www.isitopendata.org/ (still online but now static).

This allowed you do "Openness of data requests" to organizations. No legal support was there but it was still really useful, and I think it still would be (cf https://github.com/datasets/registry/issues/2).

Would it be possible to use Froide for a case where we weren't emailing gov departments but just general organizations (such as the WHO, or a Publisher)?

**Comment by arnese** [comment]
I guess this is not up to date anymore.
