### ISSUE TITLE
Progress bar accessibility for crowdfunding projects

### ISSUE THREAD

**Issue by rugk** [okfde/froide#414]
E.g. here:
https://fragdenstaat.de/crowdfunding/campaign/einsatzbericht-vom-29082020-ua-zur-ersturmung-der-reichstagstreppe-durch-rechtsextreme/

This is the code for the progress bar:
```html
<div class="progress" style="height: 25px">
    <div class="progress-bar" role="progressbar" title="Betrag erhalten" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
    
      <div class="progress-bar progress-bar-striped progress-bar-animated" title="Unbestätigte Beträge" role="progressbar" style="width: 24%" aria-valuenow="24" aria-valuemin="0" aria-valuemax="100"></div>
    
  </div>
```

I have not tested it, but I doubt these are useful values in the aria tags there. Basically it says:
* first bar ("Betrag erhalten"): from 0 to 100, currently 90
* second bar ("Unbestätigte Beträge"): from 0 to 100 (again?), currently 24

So the bar may be 200% and 24% are "unbestätigt" while 90% are "Beitrag erhalten"? Uhm…

That's not how it looks visually. Here is how it looks:
![image](https://user-images.githubusercontent.com/11966684/106581151-d7574600-6542-11eb-91a1-a4c3d86ee158.png)
 
I guess it should do some calculations and use 100% for the whole bar and then just subtract the values that it displays, actually.
Also note you don't have to use percentages there, you can (and probably should) use `aria-valuetext` for a textual representation of the data shown.

See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_progressbar_role

**Comment by stefanw** [comment]
You are probably right. The progress bar is just copied from [bootstrap examples](https://getbootstrap.com/docs/4.3/components/progress/#multiple-bars).

**Comment by rugk** [comment]
Well… okay, then it is may be correct. They do [it the same way in v5](https://getbootstrap.com/docs/5.0/components/progress/#multiple-bars).
It is however only correct if each progress bar is considered to be 100% of everything i.e. the parent element.

---

Now that I have written the upstream report (https://github.com/twbs/bootstrap/issues/32973), I think they meant the example differently. In our case the progress bar is not mutually exclusive, i.e. it's two progresses shown in one state – whereas they maybe included a kind of "pie chart" with different parts of one progress.
So the example just does not document what the progress multi-bars are used here for.

More in the upstream report, let's see what they say.

**Comment by stefanw** [comment]
Removed the max/min values and improved labels in okfde/froide-crowdfunding@8c70f66ec0c8ff3cb7f714d73185c8a20ea83802

If there's something nicer to be done, let me know.

**Comment by rugk** [comment]
Yeah, IMHO removing them altogether would not have been necessary, it just needs some calculations. (i.e.  
But given the labels are nicer now, too, I guess that's a big improvement in any case. :smiley:

**Comment by patrickhlauke** [comment]
> You are probably right. The progress bar is just copied from [bootstrap examples](https://getbootstrap.com/docs/4.3/components/progress/#multiple-bars).

but i'll note that, regardless of where you copied it, you still ended up with a bar that has one element that styled to be `width:90%`, and another stacked next to it styled to be `width:24%`. even leaving aside the ARIA aspect, this is even wrong from a styling / logic point of view.
