### ISSUE TITLE
Crowdfunding does not show the confirmed ("bestätigt") amount

### ISSUE THREAD

**Issue by rugk** [okfde/froide#415]
E.g. here:
https://fragdenstaat.de/crowdfunding/campaign/einsatzbericht-vom-29082020-ua-zur-ersturmung-der-reichstagstreppe-durch-rechtsextreme/

Currently this is shown like that:
![solid blue bar + shaded blue bar](https://user-images.githubusercontent.com/11966684/106581151-d7574600-6542-11eb-91a1-a4c3d86ee158.png)
 
## What it does show:
* What amount is pledged in total (what is donated or about top be donated), i.e. 286,00€
* What is the target amount, i.e. 250€

However, what is not show is the amount of the solid blue bar, i.e.:
* What amount of money is already payed.

Note this made me look into the source code, which also shows no value, but I found https://github.com/okfde/froide/issues/414. :smiley:

**Comment by arnese** [comment]
This is fixed by now.
