### ISSUE TITLE
Happy ILoveFs-Day 2021!

### ISSUE THREAD

**Issue by rugk** [okfde/froide#419]
Hi,
I'd just like to take a moment to say thanks for creating and maintaining [Froide](https://github.com/okfde/froide), the software behind FragDenStaat!
Thanks for OKFN/FragDenStaat to make it possible and thanks to @stefanw for big part of the development work!
I guess everyone in this forum likes what FragDenStaat offers and your software is maybe one of the most important fundaments to make that possible. It is super easy and intuitive to use and makes the "inquiry work" a lot easier. Just imagine if you had to use a normal email inbox for this. :upside_down_face: 
I, too, have probably learned to appreciate this more and more recently.

So thanks for open-sourcing the software, (I know you probably take it for granted, but it is not) and I hope it might find further distribution/application in other projects!

Keep up the good work and let's keep liberating lots of information! :blush: 
Thus, I wish you all a happy [ILoveFs day 2021](https://fsfe.org/activities/ilovefs/)!

---

[German version in the forum](https://forum.okfn.de/t/happy-ilovefs-day-2021/1289?u=rugk).

**Comment by arnese** [comment]
Thank you! :)
