### ISSUE TITLE
Opengraph meta tags

### ISSUE THREAD

**Issue by rugk** [okfde/froide#425]
The [Opengraph meta tags](https://ogp.me/) are missing for individual requests.
It would be great if you could add them, so social media & co can render better links/preview cards etc.

E.g. your own forum software Discourse uses that for OneBoxes. It currently may display this error: 
> Sorry, we were unable to generate a preview for this web page, because the following oEmbed / OpenGraph tags could not be found: description, image 

IMHO this is the best argument for including them, as of course previews [in your forum](https://forum.okfn.de) would be nice. :slightly_smiling_face:

**Comment by arnese** [comment]
closed in https://github.com/okfde/froide/commit/f7eef6d50bc78752bbd223b801a0e9c34cfbd4c0
