### ISSUE TITLE
Add a report function for comments

### ISSUE THREAD

**Issue by pajowu** [okfde/froide#438]
Some comments (like https://fragdenstaat.de/anfrage/prufung-der-lucaapp-und-weiterer-systeme-1/#nachricht-581473 ) are not helpful, but spam or harmful. It might be nice to have a option to report a comment by itself, not the message the comment was posted on.

**Comment by arnese** [comment]
Thank you. Do you think that's needed with the new request page design as well? https://fragdenstaat.de/anfrage/prufung-der-lucaapp-und-weiterer-systeme-1/#nachricht-581473

**Comment by arnese** [comment]
Closing this because I don't think we need this with the new design anymore (and we took care of the comment in question).
