### ISSUE TITLE
[UX] Revert redaction feature is not self-explaining

### ISSUE THREAD

**Issue by rugk** [okfde/froide#439]
I just stumbled over this apparently new feature:
![grafik](https://user-images.githubusercontent.com/11966684/114048673-13808d00-988b-11eb-8fab-cde25c1c44c1.png)

First of, all that's great! And I really like that I can undo my edits now. :smiley: 

I have to say, however, it's not self-explaining to me.

Problems:
* The icons are the ones used for media players (track selection/next track) or so, so I did not grasp what that was supposed to do. Better use arrows, like all other programs do. Here is e.g. a screenshot from LibreOffice:
  ![grafik](https://user-images.githubusercontent.com/11966684/114048999-57739200-988b-11eb-87ec-41f07e7553d5.png)
* The title text for the right one of these buttons, i.e. to one to "revert the revert", i.e. re-apply the redaction, says "Repeat" ("Widerholen" in German). Obviously, that's not what it does, it does not repeat anything, it just reverts the reversion.
  Again, LibreOffice e.g. calls this "Wiederherstellen", i.e. "restore" in English.

**Comment by stefanw** [comment]
The feature itself is actually as old as the redaction itself. :)

We are currently using [FontAwesome 4](https://fontawesome.com/v4.7.0/).

Unfortunately, in that icon set the [undo icon](https://fontawesome.com/v4.7.0/icon/undo) is the same as the rotate icon. So using the 'undo' icon would not make this really clearer in a context where rotating an image could be a valid action (and actually is part of the upload component).

[So in this commit](https://github.com/okfde/froide/commit/aa62398990f67f5d4cf89a5d2e277bd94d9bc58c) the icon was changed to the media-player like icons (`step-forward`/`step-backward`) which – to my mind – works relatively better. Suggestions welcome. The labels should definitely be improved.

**Comment by rugk** [comment]
> The feature itself is actually as old as the redaction itself. :)

Am I blind? I could swear this was new… I remember I usually reloaded due to the fact such a feature was missing – at least I thought so.
But well… in such a case this is just more evidence of UX-improvments that could be made here. :sweat_smile: 

---

Oh the FontAwesome icon is indeed unfortunate…

Options:
* updating to FA v5 [would not help, as it seems](https://fontawesome.com/icons/undo?style=solid)… though `backspace` looks quite good there. (but of course the reverse action is not really easy…)
* generally though, if you search for `back` there are quite some options. Maybe ` chevron-left ` – though I agree it's never optimal, as we also don't want to imply any "back navigation".
*[can't we use another icon](https://www.flaticon.com/search?word=undo), the thing LibreOffice shows is really clear and something else than those FontAwesome icons… argg…
* looking at more realistic other [glyph fonts](https://glyphsearch.com/?query=undo&copy=name) `ionicons` e.g. has that one in `ios-undo` or maybe even better IcoMoon with `undo-2` (search for "redo" to get the reverse icon)

---

Anyway, I consider this a (UX) bug in FontAwesome. As such, I've reported it in https://github.com/FortAwesome/Font-Awesome/issues/17803 to them and in https://github.com/ForkAwesome/Fork-Awesome/issues/288 for ForkAwesome, as they have the same issue and could be a (drop-in, possibly) alternative I know of.

**Comment by rugk** [comment]
A workaround [has been suggested](https://github.com/FortAwesome/Font-Awesome/issues/17803#issuecomment-816495366):

> I think that you can use a flipped version of [fa-share](https://fontawesome.com/icons/share?style=solid)
>
> https://jsfiddle.net/tagliala/zvkwmf1L/3/
