### ISSUE TITLE
Text redaction problems for long texts

### ISSUE THREAD

**Issue by rugk** [okfde/froide#443]
If you copy and paste your 5 pages long FOI appeal into the Froide, the text redaction seems to get a problem:

See here:
https://fragdenstaat.de/anfrage/sap-cwa-jira-tickets-zu-den-themen-f-droid-vollkommen-quelloffener-software-und-reproduzierbare-builds-corona-warn-app/#nachricht-592041

This is how it publicly looks like:

* The greeting is (correctly) censored: 
 ![grafik](https://user-images.githubusercontent.com/11966684/116469915-0a278680-a873-11eb-9d0e-e119e8d72c77.png)
* The ending is not, though:
  ![grafik](https://user-images.githubusercontent.com/11966684/116469990-1d3a5680-a873-11eb-810d-a2a9d69c4af6.png)
  (Good I did use `X` there :sweat_smile:)
  
Here is what – in the private view – the redaction tool, shows me:
* greeting is correct:;
  ![grafik](https://user-images.githubusercontent.com/11966684/116470105-42c76000-a873-11eb-902a-9fc523332d55.png)
* the closing is _incorrectly_ (?) shown as redacted:
  ![grafik](https://user-images.githubusercontent.com/11966684/116470152-51ae1280-a873-11eb-81a6-91dfecb272cc.png)

**Edit:**Also, BTW, when you change the text and edit it, all your redactions are gone – which is, while technically understandable for me – likely a surprising thing for many users. Or at least some unfortunate thing…

**Comment by stefanw** [comment]
We introduced cached rendering for long messages recently, because determining redactions can be CPU heavy for long texts. Cache invalidation was broken here, should be fixed now. Cache has been invalidated for all edited/redacted messages since the introduction of redaction render caching.
