### ISSUE TITLE
In neuer Ansicht wird als Anrede an die Behörde "Sehr Antragsteller/in" angezeigt

### ISSUE THREAD

**Issue by thielema** [okfde/froide#446]
Beispiel: https://fragdenstaat.de/a/220434

Als Anrede steht da in der Zusammenfassung "Sehr Antragsteller/in".

In der ausführlichen Ansicht weiter unten steht aber die richtige Anrede "Sehr geehrte Damen und Herren!"

**Comment by caffeineFox** [comment]
Wünschenswert wäre in dem Zuge noch die Anpassung auf "Antragsteller*in".

**Comment by arnese** [comment]
Ist gefixt.
