### ISSUE TITLE
Sharing dialogue doesn't copy any text

### ISSUE THREAD

**Issue by MatthiasMoeser** [okfde/froide#448]
![Screenshot_20210607-125715](https://user-images.githubusercontent.com/8005930/121005361-422dbd80-c77f-11eb-84b4-b3e86fc08270.png)
After sending one request and trying to send another, this really cool dialogue comes up.
when clicking SMS or email (don't have WhatsApp) the redirect works, but no text or URL is copied. 
I'd be glad if there were some text template with the crucial info. This way I need to type myself and we all know how hard that is.

**Comment by stefanw** [comment]
The `sms` scheme is fickle. It has now been replaced by the native `navigator.share`.
