### ISSUE TITLE
Icon "status-user_withdrew_costs" is used but not in css

### ISSUE THREAD

**Issue by shukari** [okfde/froide#449]
Fragdenstaat.de is using this icon (status-user_withdrew_costs) but there is no css definition so it is empty.
Edit: I see now the svg is missing

https://github.com/okfde/froide/blob/58a8b6014c32a023ad833bbff2f4cf5fdd7bafb0/frontend/styles/components/request-status.scss#L41-L43

**Comment by arnese** [comment]
This is fixed now.
