### ISSUE TITLE
Zeitliche Begrenzung von Nachrichten zu eng

### ISSUE THREAD

**Issue by amigalemming** [okfde/froide#451]
Ich bin gerade dabei, bei einer Reihe unbeantworteter Anfragen auf FragDenStaat.de eine Erinnerung zu versenden. Da bekomme ich als Antwort:
"Sie haben die Begrenzung von 2 Anfragen in 5 Minuten überschritten. Dies ist eine automatische Vorsichtsmaßnahme."
Das finde ich etwas eng bemessen, weil Erinnerungsmails dank FragDenStaat sehr einfach und schnell zu versenden sind.

**Comment by alehaa** [comment]
Die Begrenzung ist eine [Konfiguration von FragDenStaat.de](https://github.com/okfde/fragdenstaat_de/blob/master/fragdenstaat_de/settings/base.py#L492), dieses Repository behandelt hingegen die zugrunde liegende Software. Ich würde das Issue daher stattdessen dort aufmachen, oder ggf. auch zunächst [im Forum](http://forum.okfn.de) diskutieren.

**Comment by arnese** [comment]
Dies werden wir erstmal nicht ändern. Wer aus guten Gründen von den Begrenzungen ausgenommen werden will, kann sich per Mail an uns wenden. (siehe auch https://fragdenstaat.de/hilfe/erste-anfrage/wie-viele-anfragen-kann-ich-stellen/)
