### ISSUE TITLE
Show button to edit attachments ("Anhänge verwalten") also when there are no attachments

### ISSUE THREAD

**Issue by rugk** [okfde/froide#460]
## Problem

1. I added a "mail received" ("Post erhalten") mail entry to a FOI request. Do not add any documents and just always press "Continue". The use case here may be that you've got 500 pages of a mail and want to scan it in later, because that's way too much work. As such, you only want to document that you've got the results.
2. Now, on the main request page again, try to add these documents, after you've scanned them.

**What happens:** You find no button to do so. UI-wise, you can only edit or add attachments, if you've initially added at least once. Even for letters.

## Workaround

You can manually adjust the URL to get to the website for uploading.

Go to the message via the sidebar or so, so you get a direct link like this:
https://fragdenstaat.de/anfrage/weisung-des-bmi-betreffend-uberprufung-der-luca-app-2/#nachricht-634277

Now use the number at the end to form the following URL:
https://fragdenstaat.de/anfrage/weisung-des-bmi-betreffend-uberprufung-der-luca-app-2/634277/upload

That's it, there is the upload form.

## Suggested solution

Do show the button to edit attachments always?
At least when the type is a letter, IMHO, it is more than appropriate.

## Alternative solutions

Require people to upload an attachment when attaching a letter? -> IMHO prevents the legitimate use case I outlined above.

**Comment by alehaa** [comment]
I'd like to add, that if there's already an attachment uploaded, the upload page doesn't have a button to add new attachments, just to manage existing ones.

**Comment by rugk** [comment]
@alehaa There should be a drag- and drop zone including an optional "legacy" file-selctor behind the link for that at the bottom:
![image](https://user-images.githubusercontent.com/11966684/135695004-1aeda42c-51d4-4e3d-8fd4-6817be5eb6c1.png)

In my case, that is always there.

**Comment by alehaa** [comment]
Not in Safari. Maybe this feature is browser specific?

![screenshot](https://user-images.githubusercontent.com/6250567/135695363-ce87246a-a770-4cca-ae64-05da6fc38252.png)

**Comment by pajowu** [comment]
@alehaa the upload form is not shown on this foi request [because it is only shown on answers received via (snail) mail](https://github.com/okfde/froide/blob/89d607f0cd7b51426805ae6cbc9aca3ca954e928/frontend/javascript/components/docupload/document-uploader.vue#L80)

**Comment by stefanw** [comment]
https://github.com/okfde/froide/commit/e66aec0dff966a887a029311e5e848a4f01a8934 should solve the problem.
