### ISSUE TITLE
ohne Cookies lassen sich Nachrichten bei Anfragen nicht ausklappen

### ISSUE THREAD

**Issue by dj00686** [okfde/froide#463]
Mir ist aufgefallen, dass sich die einzelnen Nachrichten einer beliebigen Anfrage auf fragdenstaat.de nur ausklappen und damit lesen lassen, wenn man im Browser für die Domain fragdenstaat.de Cookies zulässt. Die daraufhin gesetzten Cookies haben die Namen "csrftoken" und "django_language". 
Ich sehe jetzt nicht so richtig einen legitimen Grund, warum man als nicht angemeldeter Besucher Cookies zulassen müssen sollte, nur um den Inhalt einer Webseite lesen zu können. Ich nehme nicht an, dass es sich dabei um ein gewolltes Verhalten handelt, vielleicht kann man dem mal auf den Grund gehen.

**Comment by stefanw** [comment]
Das Ausklappen von Nachrichten hat nichts mit Cookies zu tun. Offenbar blockierst du nicht nur Cookies, sondern auch `localStorage`. `localStorage` merkt sich, welche Nachrichten aufgeklappt sind, aber eben nur lokal in deinem Browser, die Daten gehen nicht zum Server (wie bei Cookies). Das zum Aufklappen notwendige JavaScript warf einen Fehler, wenn der Zugriff auf `localStorage` blockiert war. Das ist nun behoben.

Die Cookies, die wir auch ohne user session setzen, sind rein funktional: `django_language` merkt sich die bevorzugte Sprache auf der Seite (FragDenStaat gibt es auch auf Englisch) und `csrftoken` sichert Formularabsendungen gegen Cross Site Request Forgery ab.
