### ISSUE TITLE
Feature request: Add option(s) to change name

### ISSUE THREAD

**Issue by Unip0rn** [okfde/froide#466]
# The Behaviour I see

When in the settings, there is option to change personal info, but not the name.

# The Behaviour I want to see

When in the settings, there is an option to change personal info, including the name.

# Reasons

Especially but not only people who are transgender or change their legal family status (e.g. through marriage) may at some point in their life want to change their first or last name. While often there are restrictions to doing that change so that the state accepts it, This software should respect everyone, regardless of their history in gender and names. While it may be possible to just get a new account with the correct name, People affected by this may prefer to keep all their FOI requests in one place and avoid having to login to an account deadnaming them.
In case of marriage there may also arise difficulties to deliver paper mail to a place that no longer lists their name.

# Expected Efforts required

There are several places that I am aware of that use the name in one way or another. I will list them without claiming the list is concluding:

- the email adress
- the place where your profile options are (top right corner)
- the templates for requests

Special difficulty may arise from how to handle requests that are ongoing at the time of the change. A preferred course of action probably also differs depending on what part of the name is changed and possibly the reasoning of the user. 
A definite answer on that topic however requires insight into the code that I currently can not offer.

**Comment by arnese** [comment]
Thank you! We are aware of the issue and we want to change this. One additional problem connected to this is security-related, though: If requests are filed with the name anonymized to the public, FragDenStaat has to anonymize both the old and the new name. And if the e-mail address is changed in the course of the name change, we have to create alias e-mail addresses (or something like that).
At the moment, we do change names manually on request by e-mail.

**Comment by Unip0rn** [comment]
Thank you for such a quick response and taking onto the issue before I noticed! Is there a reason not to announce this situation in some way or another in the website for the meantime (besides noone did the changes yet, I get that :) )? If adding a link to this issue would work for you that might even be a change I SHOULD be able to provide.

**Comment by arnese** [comment]
We have announced it here: https://fragdenstaat.de/hilfe/funktionen-der-plattform/namen-aendern/
But it's true that's not very prominent. You are probably hinting at putting it on the profile page directly, right?

**Comment by Unip0rn** [comment]
Yes, I think that would be ideal as this is where I'd look for that option. 
Also given you have a help page on it I change my suggestion from a link to this issue to that help page as to me it makes more sense to me to link to your own site rather than here.

**Comment by stefanw** [comment]
There is now a link in the settings next to the name to the help page explaining what to do to change the name.

Another other reason why we don't offer self-service name changes: we don't want people to abuse it to have multiple personas for different requests, they will inevitably fail to their name change back to the one they used with one request before sending another message in there. The redaction tracking nightmare Arne mentioned comes on top.

As a user you will not change your name very often in your life, so handling this via support emails seems OK both from the user perspective and from the support workload.
