### ISSUE TITLE
Bei Anfragestellung Verweis auf Anfragen an die entsprechende Behörde

### ISSUE THREAD

**Issue by amigalemming** [okfde/froide#471]
Wenn ich eine Anfrage stelle, steht ganz oben:

"Schreiben Sie die Anfrage

An: Behörde XYZ"

Ich hätte gerne, dass "Behörde XYZ" mit einem Hyperlink auf die Anfragen an diese Behörde oder aber auf die Behördenseite bei FragDenStaat unterlegt ist. Dann kann ich schnell kontrollieren, welche Anfragen an diese Behörde bereits gestellt wurden. Spätestens wenn ich unten lese "Bitte stellen Sie sicher, dass die benötigten Informationen nicht schon angefragt wurden oder schon öffentlich sind" möchte ich gerne schnell die FdS-Anfragen an diese Behörde sehen.

**Comment by paradx** [comment]
since froide is internationalized and written in english, a quick summery of this issue in english: 

Feature request to add a link to the organization/agency a request is made to, to allow quicker cross checking if similar request where made in the past and to prevent duplicates.
