### ISSUE TITLE
404 link for change name help page

### ISSUE THREAD

**Issue by rugk** [okfde/froide#481]
## STR

0. Next to your full/user name on https://fragdenstaat.de/account/settings/ there is a question mark. (?)
1. Click on it.

## What happens

You get to https://fragdenstaat.de/hilfe/funktionen-der-plattform/namen-aendern/, which shows a 404 error, so no help is there?

## What should happen

link to the correct help site?

**Comment by stefanw** [comment]
Cannot reproduce, link works for me (and also without being logged in).
Here's an archive.org version as proof that it is indeed public:
https://web.archive.org/web/20220208212534/https://fragdenstaat.de/hilfe/ihr-konto-verwalten/namen-aendern/

**Comment by rugk** [comment]
Woha, lol, now it also works here. I swear it did not work when I created the issue…
