### ISSUE TITLE
Allow more (any?) file types for file uploads / attachments

### ISSUE THREAD

**Issue by jfilter** [okfde/froide#494]
A public body sent a XLSX file to a FOI request by snake mail / private mail. It's impossible, to add it as an attachment to a request because only PDF / images are allowed.

**Comment by stefanw** [comment]
Individual messages can now be configured to receive extra file types as attachments. Please open a problem report on the message in question with the file type you wan to upload.

**Comment by jfilter** [comment]
That's the spirit. 👍
