### ISSUE TITLE
Disable or Spam-proof Foi Request Follows

### ISSUE THREAD

**Issue by fin** [okfde/froide#517]
At FragDenStaat.at, we're getting quite a lot of submissions to /benachrichtigungen forms, which do not seem to be getting confirmed. Sadly, one IP only does 2-3 requests with the same Email. There is no global flag for disabling the feature, right?

I haven't looked into how the signup form is different, because we don't have any issues there.

Some of the IPs seem to be blocked by DNSBLs at least, so that would be one way to spam-proof.

Setting nginx to block requests to `/benachrichtigen` seems to help for now though (:

**Comment by stefanw** [comment]
We recently uncoupled the following system,  so code may be different from your deployment, but there are some spam fighting settings. Check out `froide.helper.spam`. Specifically setting `target_countries` in `FROIDE_CONFIG` like in `fragdenstaat_de/settings/base.py` checks if the request IP is geolocated in one of these countries via `geoip` and if not it shows a “captcha” (effective against generic bots).

The spam settings per form could be made configurable (for following see `froide/follow/forms.py`) to become more aggressive if required.
