### ISSUE TITLE
Messages from Commissioners shouldn't always be non-public at first

### ISSUE THREAD

**Issue by arnese** [okfde/froide#528]
At the moment, e-mails from information commissioners are non-public by default. That's useful because we want mediation processes to be confidential. However, e-mail responses from commissioners to requests directed at them are non-public now as well until published manually by the requester (https://fragdenstaat.de/behoerde/305/bundesbeauftragter-fur-den-datenschutz-und-die-informationsfreiheit/).

Solution: There should be an exception to the non-public feature - when requests are aimed at the commissioner directly, requests should be public like in all other requests.

**Comment by pajowu** [comment]
If the commissioner does not handle the FOI request well, is it possible to ask for mediation? And if yes from who? If this is handled by the same commissioner, should the mediation be private or public?

**Comment by arnese** [comment]
Sneaky. Yes, it's possible to ask for mediation and it's the same commissioner (but usually someone else internally). But if that's what you are going for: In these cases the mediation can be public by default as well because within the authority, there's no confidentiality anyways.
