### ISSUE TITLE
Add the rss feeds to the <header> for easy subscribing

### ISSUE THREAD

**Issue by TheRadialActive** [okfde/froide#529]
Thank you very much for creating this project and adding rss feeds to the interface.

The blog (https://fragdenstaat.de/blog/) already has the feed link in the header.
`<link rel="alternate" type="application/rss+xml" title="FragDenStaat Blog" href="/blog/feed/" />`

Could we also add that to the header of the institutions and organisations like https://fragdenstaat.de/behoerde/bundesministerium-des-innern/ ?

PS: It would be also great to provide an rss feed even for institutions, who don't have any requests - for future ones.

**Comment by pajowu** [comment]
Closed by https://github.com/okfde/froide/commit/ee01abfdd265569657dbe0bc8c1c355faaf3585c
