### ISSUE TITLE
[Feature] add sorting option "Recently updated"

### ISSUE THREAD

**Issue by foss-** [okfde/froide#530]
Hope this is the correct repo for this feature request. For search results it is useful, when someone is interested in recent activity in regards to their search term, to have an option, allowing to sort after `Recently updated` (like e.g. this GitHub issue tracker allows).

**Currently**
Don't think this option exists.
![Screenshot 2022-05-17 at 12 20 30](https://user-images.githubusercontent.com/5708172/168789858-4c2a1460-2b54-45ce-bf40-60c7061b9f11.png)

**Expected**
Would be great to add such an option.

**Comment by pajowu** [comment]
We now have the option to sort by last received message. Is that what you were interested in? Or would you also want to sort by all updates (e.g. the user setting the status, updating the costs, publishing a document, receiving a comment, …)

**Comment by foss-** [comment]
Thanks so much for adding this sorting option. And thanks for following up with the more fine grained question which I can't answer. I trust your judgment and I am sure you are able to make a much saner decision on this remaining question than me.
