### ISSUE TITLE
Filing cabinet / document collection: Wrong (lexical) sort order for document groups

### ISSUE THREAD

**Issue by jfowl** [okfde/froide#541]
I would expect the list to be sorted from 1 to 20, instead of 10 – 20 and then 1 – 9.

Example from https://fragdenstaat.de/dokumente/sammlung/47-bundestag-untersuchungsausschusse-1-bis-20-wahlperiode/:

![image](https://user-images.githubusercontent.com/15788906/174566152-45cc8bf8-0311-4719-a61b-7f9a7afb3005.png)

Might be an issue in https://github.com/okfde/django-filingcabinet, so feel free to move it there.

**Comment by stefanw** [comment]
Import order is by lexical name, fixed it manually by reordering the directory tree.
