### ISSUE TITLE
Change naming for type of uploaded documents

### ISSUE THREAD

**Issue by teriky** [okfde/froide#549]
This change request is related to the German software version. Let's switch to German.

**Die aktuelle Umsetzung:**

Wenn ein Dokument hochgeladen wird, muss sich die Anwenderin entscheiden, ob es sich um einen emfangenen oder gesendeten _Brief_ handelt: "Ich habe einen Brief erhalten" oder " Ich habe einen Brief gesendet".

Neben Briefen existieren jedoch zahlreiche andere Dokumentenformate, die hochgeladen werden können:

- E-Mails (über andere Accounts)
- Faxe
- Fotos
- Transkripte
- ...

Insofern ist die Bezeichnung "Brief" zu spezifisch.

**Eine mögliche künftige Umsetzung:**

Nutzung des generischen Begriffes _Dokument_.

"Haben Sie das Dokument erhalten oder versendet?" : "Ich habe ein Dokument erhalten" oder " Ich habe ein Dokument gesendet".

Bereits der Begriff "Post" (verwendet bei der Beschriftung des Buttons [Post hochladen]) ist allgemeiner als "Brief".

![received-sent](https://user-images.githubusercontent.com/40558729/175015749-50e1ed4e-dc4d-4203-b0e3-a2556087ffa1.png)

**Comment by stefanw** [comment]
Mit Brief meinen wir hier (wie gemeinüblich hoffentlich verständlich) den Postbrief, also eine postale Zustellung, wie sie von Behörden häufig vorkommt. 

Wir fragen in dem Schritt Kommunikation ab: *wann* und *wie* wurde etwas empfangen oder versendet. Intern haben wir für jedes *wie* einen [Nachrichtentyp](https://github.com/okfde/froide/blob/main/froide/foirequest/models/message.py#L56-L62), u.a. E-Mail, postale Zustellung und Fax. "Foto" oder "Transkript" bildet keine Kommunikation ab. 

Wir können "Brief" in "Post" ändern, wenn das deine Verwirrung löst?

**Comment by teriky** [comment]
Dass mit Brief der Postbrief gemeint ist, war der Auslöser für meinen Vorschlag.

Eine Umbenennung in "Post" würde die Benutzeroberfläche vereinheitlichen. Das wäre m. E. ausreichend _und_ sinnvoll.

Ich gebe trotzdem mal ein Beispiel, wie bei mir häufig Dokumente anfallen, bei denen es sich um keinen Postbrief handelt..

**Beispiel: ["Klima-Gebäude-Check"-Anfrage](https://fragdenstaat.de/a/198076)**

Die Anfrage wird an eine Behörde gesendet, in der das Gebäude geografisch liegt. Oft ist aber eine andere Behörde zuständig. Da es keine Möglichkeit gibt, die Zuständigkeit zu ändern, bleibt eigentlich nur noch, die Anfrage ergebnislos zu schließen.

Das ist unbefriedigend. Inbesondere, wenn es sich um große Liegenschaften der Länder/des Bundes handelt.

Ich löse solche Anfragen wie folgt: Entweder sende ich die Anfrage per Fax oder über einen privaten E-Mail-Account an die zuständige Behörde. Das dokumentiere ich auch entsprechend durch Hochladen der jeweiligen PDFs.

Bei Anfragewiederholung per E-Mail wird manchmal sogar per E-Mail geantwortet. Die Auskunft ist dann ein Word-Dokument, ein JPG o. ä.

**Comment by stefanw** [comment]
Wenn sich eine Anfrage an die falsche Stelle richtet (und das passiert schon öfter mal, u.a. auch bei unseren Kampagnen), dann wird im besten Fall die Anfrage von der falschen Stelle an die richtige Stelle weitergeleitet (wie üblicherweise im Anschreiben gewünscht) oder die Anfrage kann als "Information nicht vorhanden" geschlossen werden. Dann lässt sich eine neue Anfrage an die richtige Stelle stellen.

Eine externe Anfragewiederholung und dann das Einpflegen von externer Nicht-Post-Kommunikation ist einfach momentan nicht vorgesehen. FragDenStaat gibt es ja, damit man eben nicht externe Kommunikation einpflegen muss (dass es Postantworten noch braucht ist ein Bug in der deutschen Bürokratie).

Anstelle des perfekten Abbildens aller Kommunikation, gehen wir gerade eher in die Richtung, die Darstellung des Ergebnisses der Anfrage zu verbessern, da diese vermutlich eher langfristig von Interesse ist.
