### ISSUE TITLE
Unable to activate 2FA with authentication app

### ISSUE THREAD

**Issue by teriky** [okfde/froide#560]
Today I've tried to activate 2-Factor-Authentication (2FA). But didn't succeed.

I'm using the Google Authenticator App.

**Steps 2 recreate:**

1. Navigate to [Authentifizierungs-App einrichten](https://fragdenstaat.de/account/mfa/create/TOTP/).
2. Capture QR code with the authentication app.
3. Enter either a (somehow required) FdS name, an email address or any other name.
4. Enter the authentication app generated code.

--> Validation fails.

I've never seen a "Name" field before when using 2FA. What kind of "name" does FdS expect? An explanation at the web page might be helpful.

![2FA](https://user-images.githubusercontent.com/40558729/181253438-42afb65d-69e3-4443-94eb-cf0f61a94f4b.png)

**Comment by teriky** [comment]
After configuring hardware tokens for 2FA I learned: The name is simple a tag. Something like "My name APP 4 auth".

**Comment by stefanw** [comment]
I just tested this and cannot reproduce. The code is only valid for 30 seconds, maybe you entered it and submitted it too late?

But thank you for the feedback. The 2FA section is quite rough around the edges and this helps to make it better.

**Comment by teriky** [comment]
Today I tried again and this time the validation succeded.
