### ISSUE TITLE
No objects shown at maps for "Topf Secret: Mission Fleisch" and "Klima-Gebäude-Check"

### ISSUE THREAD

**Issue by teriky** [okfde/froide#578]
The maps at both "Topf Secret: Mission Fleisch" and "Klima-Gebäude-Check" do not display any objects.

Steps to recreate:

1. Select "Topf Secret: Mission Fleisch"
2. Enter "Peine" as loaction
> **Expected result:** Objects like meat production facilities are displayed over the map
> **Actual result:** No objects are displayed, only the map is visible

![map Topf Secret - Mission Fleisch](https://user-images.githubusercontent.com/40558729/189137964-2e86d2af-26b1-48ad-8d39-0ab8eae60cb1.png)

Steps to recreate:

1. Select "Klima-Gebäude-Check"
2. Enter "Peine" as loaction
> **Expected result:** Objects like town halls are displayed over the map
> **Actual result:** No objects are displayed, only the map is visible

![map Klima-Gebäude-Check](https://user-images.githubusercontent.com/40558729/189138444-a5ee3328-421d-43a0-a484-3370c61e9dfa.png)

The map of "Topf Secret" still works as expected:

1. Select "Topf Secret"
2. Enter "Peine" as loaction
> **Result:** Objects like restaurants are displayed over the map

![map Topf Secret](https://user-images.githubusercontent.com/40558729/189138997-0fd50668-7800-4c8f-9742-9f0db6811cc5.png)

**Comment by stefanw** [comment]
Thanks! Fixed in okfde/froide-campaign@d6b30a4fb1e579fc295c9e20e60fceff660ca563.
