### ISSUE TITLE
nice-to-have: Kurz-URL's für fragdenstaat.de-Anhänge einblenden

### ISSUE THREAD

**Issue by HappyPony** [okfde/froide#58]
Wenn man die Anhänge von der fragdenstaat.de-Website verlinkt, dann sind die daraus generierte Verweise in Emails unbrauchbar, da an falschen Stellen, z.B. nach einem "-" umgebrochen wird. Es wäre hilfreich, wenn die  fragdenstaat.de-Lösung pro Anhang eine Kurz-URL generiert und diese URL dann neben bzw. unter dem Anhang im Anfrage-Thread einblendet. Für die Realisierung dieser Anregung ist vermutlich die bereits vorhandene Lösung, die Kurz-URL's für jede fragdenstaat.de-Anfrage erstellt und breitstellt, wiederverwendet werden.

**Comment by jfilter** [comment]
Ich verstehe nicht ganz deinen ersten Punkt. Die URLs für Anhänge sind defekt, wenn man sie in Emails benutzt?

Asonsten gibt's es sicherlich Anwendungsfülle für Kurz-URLs, aber ich glaube man kann einfach [einen bestehenden Service](http://google.com/search?q=url+shortening) nutzen.

**Comment by arnese** [comment]
Yup, not needed.
