### ISSUE TITLE
Manage documents: Menu for redacted documents does not open

### ISSUE THREAD

**Issue by teriky** [okfde/froide#585]
Steps to reproduce:

1. Navigate to "manage documents" with an (already) redacted document.
2. Click on the arrow button behind the redacted document.
**Expected behavior:** A menu opens with entries like "Delete", "Redact".
**Actual behavior:** Menu does _not_ open.

![submenu](https://user-images.githubusercontent.com/40558729/190085693-afbd79ad-76b1-451e-90c1-a8da95d5caac.png)

Additional information:

- Browser: Firefox 104.0.2 (64-Bit)
- Other Menus open when clicked.

**Comment by stefanw** [comment]
Thanks for reporting! Was caused by our recent transition to Bootstrap5.
