### ISSUE TITLE
Provide additional information if the number of requests per time has been exceeded

### ISSUE THREAD

**Issue by teriky** [okfde/froide#590]
_The challenge:_

The number of requests in a given time frame is restricted (e. g. 8 per day, 20 per week). When exceeding this number a user gets a message like "You have exceeded the limit of 20 requests in 1 week. This is an automatic precaution."

![lock message](https://user-images.githubusercontent.com/40558729/190356788-5496bd4d-8717-4b12-ba5d-48b021367748.png)

Without additional information one can only guess when a new request can be sent. Even with the knowledge of one's sent requests it can be difficult to determine the release of this lock.

_A solution:_

Provide additional information like "Your next request can be sent on [datetime]." ("Ihre nächste Anfrage kann am [Zeitpunkt] gesendet werden.").

**Comment by cpresser** [comment]
It would also be nice to have a way to disable that limit, or increase its size. 

Assuming there are two questions, but I want them answered in each Bundesland, thats already more than 20 requests on one day.

**Comment by arnese** [comment]
We should probably link to this: https://fragdenstaat.de/hilfe/erste-anfrage/wie-viele-anfragen-kann-ich-stellen/
