### ISSUE TITLE
Schwärzung wird gelegentlich versehentlich wieder aufgehoben

### ISSUE THREAD

**Issue by amigalemming** [okfde/froide#619]
In dem Schwärzungstool hakt es in letzter Zeit häufig. D.h. ich ziehe ein schwarzes Rechteck auf, aber wenn ich die Maustaste loslasse, verändert sich das Rechteck immer noch. Oder ich lasse die Maustaste los und das Rechteck bleibt fest, aber wenn ich daraufhin zur nächsten Seite wechsle, hängt das Rechteck wieder am Mauszeiger und wenn ich dann das Rechteck "festklicke", dann ist es auf einmal auf der Seite davor verändert.
Ich befürchte, dass einige Dokumente nicht korrekt geschwärzt sind, weil Benutzer nicht gemerkt haben, dass das Schwärzungstool eine Schwärzung unbemerkt wieder aufgehoben hat.
Ich benutze Firefox ESR 102.5 (Debian Bullseye).

**Comment by stefanw** [comment]
Es gab keine signifikaten Änderungen am Schwärzungs-Tool im letzten Jahr. Das alles klingt eher so, als würden die Klicks deiner Maus nicht erkannt werden? Wenn du ein Touchpad nutzt, kann es auch unterschiedliche Click-Drag-Release-Einstellungen geben (z.B. bei mir kann ich doppel-tappen um einen Drag-Vorgan zu starten. 

Ich habe ein paar Änderungen vorgenommen, die den Drag-Vorgang besser abbrechen sollten.
