### ISSUE TITLE
Sort options based on request date don't work as expected

### ISSUE THREAD

**Issue by teriky** [okfde/froide#623]
Steps to reproduce:

- open the requests page of "Ministerium für Justiz und Gesundheit" (https://fragdenstaat.de/anfragen/an/ministerium-fur-justiz-kultur-und-europa/)
- click on [More search options] to display the combo box with the search options
- select "request date (newest first)"

![001 newest first](https://user-images.githubusercontent.com/40558729/203639873-843b74ff-0dd4-4838-8ca5-5628c51713e3.jpg)

- note the entry order
- change the search option to "request date (oldest first)"
- display the last result page

    -> **expected behaviour:** the last requests should be the same as above in reverse order
    -> **actual behaviour:** other requests are displayed

![002 oldest first](https://user-images.githubusercontent.com/40558729/203639884-e6b7c31e-093b-48b5-a33d-82e09b7fb99d.jpg)

With sort order "request date (newest first)" the request "Anzahl VIG-Anfragen über FragDenStaat" (#262721) with request date 08.11.2022 is missed.

**Comment by pajowu** [comment]
We did some changes to the filter & sorting code, which seems to have fixed this (at least I could not reproduce it). Could you please check again and close the issue if the problem no longer exists?

**Comment by pajowu** [comment]
Please feel free to re-open this if you find this issue persists
