### ISSUE TITLE
Filters dropped when navigating to further pages

### ISSUE THREAD

**Issue by michael-schwarz** [okfde/froide#678]
When filtering results, e.g., for state `Anfrage erfolgreich` the pagination links at the bottom lead to unfiltered results.

**Steps to reproduce**:

- Filter,  e.g., for state `Anfrage erfolgreich`:  https://fragdenstaat.de/anfragen/?q=&status=erfolgreich&jurisdiction=&campaign=&category=&publicbody=&tag=&user=&first_after=&first_before=&sort=)
- Click on link to second page at the bottom leads to https://fragdenstaat.de/anfragen/?page=2 (unfiltered results)

When manually appending `&page=2` to the URL for filtered results, one gets the second page of the filtered results as expected.

**Affected browsers**:
- Chrome Version 109.0.5414.119 (no active extensions)
- Mozilla Firefox for Ubuntu 110.0.1 (64-bit) canonical - 1.0

**Comment by pajowu** [comment]
Thank you for reporting this. This issue seems to have been introduced when we reworked the faceting code to fix some other issues with the search in #651. I'm currently working on a fix and hope to have it ready soon.
