### ISSUE TITLE
Add info about absent of opposition proceedings (Widerspruchsverfahren) in Hessen

### ISSUE THREAD

**Issue by codedust** [okfde/froide#713]
According to https://forum.okfn.de/t/kein-widerspruchsverfahren-in-hessen/350/2, there are no opposition proceedings (Widerspruchsverfahren) in Hessen. This information would be very helpful in this article: https://fragdenstaat.de/hilfe/tipps-fur-den-anfrageprozess/widerspruch/

**Comment by pajowu** [comment]
Thanks for opening this issue. Since then, a sentence on this topic was added to the help page
