### ISSUE TITLE
Anfragen brauchen Ihre Aufmerksamkeit! 

### ISSUE THREAD

**Issue by HappyPony** [okfde/froide#79]
Wenn ich meine Account-Seite https://fragdenstaat.de/account/ anzeige, werden mit der Aufschrift "X Anfragen brauchen Ihre Aufmerksamkeit!" die Anfragen aufgelistet, bei den die Behörden die Monatsfrist verstreichen ließen.

Ich habe gestern das Formular "Ihre Anfrage ist verspätet. Sie sollten der Behörde eine Nachricht schicken." genutzt und an alle Behörden aus der Liste oben Erinnerungsnachrichten geschickt. Was mich irritiert, dass:
1) die eingangs erwähnte Liste  "X Anfragen brauchen Ihre Aufmerksamkeit!" wird unverändert angezeigt
2)  das Formular "Ihre Anfrage ist verspätet. Sie sollten der Behörde eine Nachricht schicken." wird eingeblendet, wenn ich eine Anfrage aus der Liste 1) anklicke.

Ist das in 1) und 2) beschriebenes Verhalten das gewünschte Verhalten der FDS-Lösung oder sind es Bugs?

**Comment by arnese** [comment]
Das ist nicht mehr relevant.
