### ISSUE TITLE
Production setup instructions are incomplete

### ISSUE THREAD

**Issue by rufuspollock** [okfde/froide#82]
https://froide.readthedocs.org/en/latest/productionsetup/

Top of page lists several items at top (such as gunicorn wsgi) which have no further info further below.

**Comment by mattiasaxell** [comment]
@rgrp @stefanw this is still problematic. I believe @ryankanno has demystified the process a little bit with his [Vagrant-file](https://github.com/ryankanno/froide/blob/vagrant/Vagrantfile.README.md)!

**Comment by mattiasaxell** [comment]
@stefanw do you recommend setting up on Heroku first and then migrating to bare server when the bare server setup process has been demystified?

**Comment by guglielmo** [comment]
Hi, I am looking for a way to deploy a new instance of Froide. Would like to use Dockerfile/docker-compose, though, in order to use our infrastructure, rather than heroku (and herokudeployment instructions seem to be really old). Any hints?
