### ISSUE TITLE
Cannot upload any letters anymore (500 error)

### ISSUE THREAD

**Issue by rugk** [okfde/froide#882]
I go to https://fragdenstaat.de/anfrage/studie-umfrage-untersuchung-zur-preiserhoehung-des-deutschlandtickets-d-tickets-ehm-49eur-tickets-um-bis-zu-10eur-1/ and click on the "Upload letters" ("Post hochladen") button, which goes to https://fragdenstaat.de/anfrage/studie-umfrage-untersuchung-zur-preiserhoehung-des-deutschlandtickets-d-tickets-ehm-49eur-tickets-um-bis-zu-10eur-1/948635/postnachricht-bearbeiten/, but there I just get a 500 error:
![grafik](https://github.com/user-attachments/assets/3f349773-9450-455f-a359-84ecfd4db08f)

**Comment by pajowu** [comment]
Thank you for reporting this. We're already working on a fix

**Comment by pajowu** [comment]
will be fixed with #883
