### ISSUE TITLE
Missing static files

### ISSUE THREAD

**Issue by onny** [okfde/froide#902]
I was able to build and run Froide as a NixOS package and module https://github.com/NixOS/nixpkgs/pull/355835

After running it and visiting localhost:8000 I see this page:

![20241117_20h32m14s_grim](https://github.com/user-attachments/assets/6fb62254-18e6-456e-b963-c9733e754ee0)

Somehow it doesn't even try to load css or js files only images which are missing too

```
DJANGO_CONFIGURATION=Production manage.py migrate
DJANGO_CONFIGURATION=Production manage.py runserver localhost:8000
```

**Comment by onny** [comment]
in my package output I have:
```
ls result
bin               docs               frontend     MANIFEST.in           package.json    requirements-test.txt  vite.config.js
build             eslint.config.mjs  LICENSE.txt  monkeytype_config.py  pnpm-lock.yaml  requirements.txt
compose-dev.yaml  froide             Makefile     nix-support           pyproject.toml  SECURITY.md
dist              froide.egg-info    manage.py    node_modules          README.md       tsconfig.json
```
and
```
ls result/build/
css               fileuploader.js.map   js                  messageredaction.js      proofupload.js           redact.js
document.js       filingcabinet.js      main.js             messageredaction.js.map  proofupload.js.map       redact.js.map
document.js.map   filingcabinet.js.map  main.js.map         moderation.js            publicbody.js            request.js
docupload.js      fonts                 makerequest.js      moderation.js.map        publicbody.js.map        request.js.map
docupload.js.map  geomatch.js           makerequest.js.map  postupload.js            publicbodyupload.js      tagautocomplete.js
fileuploader.js   geomatch.js.map       manifest.json       postupload.js.map        publicbodyupload.js.map  tagautocomplete.js.map
```
hope these are the correct places to put the files in

**Comment by krmax44** [comment]
Does it work when you omit the `DJANGO_CONFIGURATION=Production` variable?

**Comment by onny** [comment]
Then it tries to load `manifest.dev.json` where as `pnpm run build` only produces a `manifest.json` file

**Comment by krmax44** [comment]
Ah, right. Try running `manage.py collectstatic` after building the frontend (see [Django docs](https://docs.djangoproject.com/en/4.2/ref/contrib/staticfiles/#collectstatic) for details). If it still doesn't work, it may be a limitation of Django's dev server (which doesn't mix well with `DJANGO_CONFIGURATION=Production`).

**Comment by onny** [comment]
Thank you, I'll use froide only as Python module for now but might come back later to package it for NixOS :)
